// Code generated by protoc-gen-go. DO NOT EDIT.
// source: geography.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Geography struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geography) Reset()         { *m = Geography{} }
func (m *Geography) String() string { return proto.CompactTextString(m) }
func (*Geography) ProtoMessage()    {}
func (*Geography) Descriptor() ([]byte, []int) {
	return fileDescriptor_e986d2946f94ff22, []int{0}
}

func (m *Geography) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geography.Unmarshal(m, b)
}
func (m *Geography) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geography.Marshal(b, m, deterministic)
}
func (m *Geography) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geography.Merge(m, src)
}
func (m *Geography) XXX_Size() int {
	return xxx_messageInfo_Geography.Size(m)
}
func (m *Geography) XXX_DiscardUnknown() {
	xxx_messageInfo_Geography.DiscardUnknown(m)
}

var xxx_messageInfo_Geography proto.InternalMessageInfo

func (m *Geography) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Geography) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Geography) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type LocationDistanceRequest struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationDistanceRequest) Reset()         { *m = LocationDistanceRequest{} }
func (m *LocationDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*LocationDistanceRequest) ProtoMessage()    {}
func (*LocationDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e986d2946f94ff22, []int{1}
}

func (m *LocationDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationDistanceRequest.Unmarshal(m, b)
}
func (m *LocationDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationDistanceRequest.Marshal(b, m, deterministic)
}
func (m *LocationDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationDistanceRequest.Merge(m, src)
}
func (m *LocationDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_LocationDistanceRequest.Size(m)
}
func (m *LocationDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LocationDistanceRequest proto.InternalMessageInfo

func (m *LocationDistanceRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *LocationDistanceRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

type LocationDistanceResponse struct {
	Geography            float64  `protobuf:"fixed64,1,opt,name=geography,proto3" json:"geography,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationDistanceResponse) Reset()         { *m = LocationDistanceResponse{} }
func (m *LocationDistanceResponse) String() string { return proto.CompactTextString(m) }
func (*LocationDistanceResponse) ProtoMessage()    {}
func (*LocationDistanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e986d2946f94ff22, []int{2}
}

func (m *LocationDistanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationDistanceResponse.Unmarshal(m, b)
}
func (m *LocationDistanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationDistanceResponse.Marshal(b, m, deterministic)
}
func (m *LocationDistanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationDistanceResponse.Merge(m, src)
}
func (m *LocationDistanceResponse) XXX_Size() int {
	return xxx_messageInfo_LocationDistanceResponse.Size(m)
}
func (m *LocationDistanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationDistanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LocationDistanceResponse proto.InternalMessageInfo

func (m *LocationDistanceResponse) GetGeography() float64 {
	if m != nil {
		return m.Geography
	}
	return 0
}

func init() {
	proto.RegisterType((*Geography)(nil), "pb.Geography")
	proto.RegisterType((*LocationDistanceRequest)(nil), "pb.LocationDistanceRequest")
	proto.RegisterType((*LocationDistanceResponse)(nil), "pb.LocationDistanceResponse")
}

func init() { proto.RegisterFile("geography.proto", fileDescriptor_e986d2946f94ff22) }

var fileDescriptor_e986d2946f94ff22 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4f, 0xcd, 0x4f,
	0x2f, 0x4a, 0x2c, 0xc8, 0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x0a, 0xe5, 0xe2, 0x74, 0x87, 0x09, 0x0b, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0xc9, 0x70, 0x71, 0xe6, 0xe4, 0xe7, 0xa5, 0x67, 0x96,
	0x94, 0xa6, 0xa4, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x06, 0x21, 0x04, 0x84, 0xa4, 0xb8, 0x38,
	0x72, 0x12, 0x4b, 0x20, 0x92, 0xcc, 0x60, 0x49, 0x38, 0x5f, 0x29, 0x98, 0x4b, 0xdc, 0x27, 0x3f,
	0x39, 0xb1, 0x24, 0x33, 0x3f, 0xcf, 0x25, 0xb3, 0xb8, 0x24, 0x31, 0x2f, 0x39, 0x35, 0x28, 0xb5,
	0xb0, 0x34, 0xb5, 0xb8, 0x04, 0xd5, 0x50, 0x46, 0x7c, 0x86, 0x32, 0xa1, 0x19, 0x6a, 0xc1, 0x25,
	0x81, 0x69, 0x68, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0xc8, 0x54, 0xb8, 0xf7, 0x60, 0xa6, 0xc2,
	0x05, 0x8c, 0xd2, 0xb8, 0x04, 0xe0, 0xbe, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x0a,
	0xe2, 0x12, 0x76, 0x4f, 0x2d, 0x41, 0x37, 0x50, 0x48, 0x5a, 0xaf, 0x20, 0x49, 0x0f, 0x87, 0xdb,
	0xa5, 0x64, 0xb0, 0x4b, 0x42, 0xdc, 0xa0, 0xc4, 0x90, 0xc4, 0x06, 0x0e, 0x58, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xae, 0x0f, 0x81, 0x49, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeographyServiceClient is the client API for GeographyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeographyServiceClient interface {
	GetLocationDistance(ctx context.Context, in *LocationDistanceRequest, opts ...grpc.CallOption) (*LocationDistanceResponse, error)
}

type geographyServiceClient struct {
	cc *grpc.ClientConn
}

func NewGeographyServiceClient(cc *grpc.ClientConn) GeographyServiceClient {
	return &geographyServiceClient{cc}
}

func (c *geographyServiceClient) GetLocationDistance(ctx context.Context, in *LocationDistanceRequest, opts ...grpc.CallOption) (*LocationDistanceResponse, error) {
	out := new(LocationDistanceResponse)
	err := c.cc.Invoke(ctx, "/pb.GeographyService/GetLocationDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeographyServiceServer is the server API for GeographyService service.
type GeographyServiceServer interface {
	GetLocationDistance(context.Context, *LocationDistanceRequest) (*LocationDistanceResponse, error)
}

// UnimplementedGeographyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGeographyServiceServer struct {
}

func (*UnimplementedGeographyServiceServer) GetLocationDistance(ctx context.Context, req *LocationDistanceRequest) (*LocationDistanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationDistance not implemented")
}

func RegisterGeographyServiceServer(s *grpc.Server, srv GeographyServiceServer) {
	s.RegisterService(&_GeographyService_serviceDesc, srv)
}

func _GeographyService_GetLocationDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeographyServiceServer).GetLocationDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GeographyService/GetLocationDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeographyServiceServer).GetLocationDistance(ctx, req.(*LocationDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeographyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GeographyService",
	HandlerType: (*GeographyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocationDistance",
			Handler:    _GeographyService_GetLocationDistance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geography.proto",
}
