// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package pkg

import (
	"time"
)

type JourneyInput struct {
	Details      string   `json:"details"`
	IsComplete   bool     `json:"isComplete"`
	IsInProgress bool     `json:"isInProgress"`
	IsStarted    bool     `json:"isStarted"`
	Type         string   `json:"type"`
	Steps        []string `json:"steps"`
	Progress     *int     `json:"progress"`
}

type LocationInput struct {
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PaginationInput struct {
	Skip *int `json:"skip"`
	Take *int `json:"take"`
}

type PostGoalInput struct {
	Creator      string        `json:"creator"`
	Aim          string        `json:"aim"`
	Participants []string      `json:"participants"`
	Likes        []string      `json:"likes"`
	Watchers     []string      `json:"watchers"`
	Reason       string        `json:"reason"`
	Inspiration  string        `json:"inspiration"`
	Details      string        `json:"details"`
	Type         string        `json:"type"`
	Tags         []string      `json:"tags"`
	SimilarGoals []string      `json:"similarGoals"`
	IsAchieved   bool          `json:"isAchieved"`
	IsPrivate    bool          `json:"isPrivate"`
	Journey      *JourneyInput `json:"journey"`
}

type PostGroupInput struct {
	Title       string   `json:"title"`
	Details     string   `json:"details"`
	Description string   `json:"description"`
	Type        string   `json:"type"`
	People      []string `json:"people"`
}

type PostPostInput struct {
	Author           string  `json:"author"`
	Anonymous        *bool   `json:"anonymous"`
	Topic            string  `json:"topic"`
	Category         string  `json:"category"`
	ContentText      string  `json:"contentText"`
	Type             string  `json:"type"`
	Latitude         float64 `json:"latitude"`
	Longitude        float64 `json:"longitude"`
	ContentPhotoName string  `json:"contentPhotoName"`
	ContentFileName  string  `json:"contentFileName"`
}

type PostSpaceInput struct {
	Creator     string     `json:"creator"`
	Topic       string     `json:"topic"`
	Details     string     `json:"details"`
	Description string     `json:"description"`
	Type        string     `json:"type"`
	Tags        []string   `json:"tags"`
	Date        *time.Time `json:"date"`
	Managers    []string   `json:"managers"`
	Followers   []string   `json:"followers"`
}

type PostTaskInput struct {
	Text string     `json:"text"`
	Date *time.Time `json:"date"`
}

type RegisterInput struct {
	Username     string `json:"username"`
	Password     string `json:"password"`
	Firstname    string `json:"firstname"`
	Lastname     string `json:"lastname"`
	EmailAddress string `json:"emailAddress"`
	Gender       string `json:"gender"`
}

type UpdateGoalInput struct {
	ID           string        `json:"id"`
	Creator      string        `json:"creator"`
	Aim          string        `json:"aim"`
	Participants []string      `json:"participants"`
	Likes        []string      `json:"likes"`
	Watchers     []string      `json:"watchers"`
	Reason       string        `json:"reason"`
	Inspiration  string        `json:"inspiration"`
	Details      string        `json:"details"`
	Type         string        `json:"type"`
	Tags         []string      `json:"tags"`
	SimilarGoals []string      `json:"similarGoals"`
	IsAchieved   bool          `json:"isAchieved"`
	IsPrivate    bool          `json:"isPrivate"`
	Journey      *JourneyInput `json:"journey"`
}

type UpdateGroupInput struct {
	ID          string   `json:"id"`
	Title       string   `json:"title"`
	Details     string   `json:"details"`
	Description string   `json:"description"`
	Type        string   `json:"type"`
	People      []string `json:"people"`
}

type UpdatePostInput struct {
	ID               string  `json:"id"`
	Author           string  `json:"author"`
	Anonymous        *bool   `json:"anonymous"`
	Topic            string  `json:"topic"`
	Category         string  `json:"category"`
	ContentText      string  `json:"contentText"`
	Type             string  `json:"type"`
	Latitude         float64 `json:"latitude"`
	Longitude        float64 `json:"longitude"`
	ContentPhotoName string  `json:"contentPhotoName"`
	ContentFileName  string  `json:"contentFileName"`
}

type UpdateSpaceInput struct {
	ID          string     `json:"id"`
	Creator     string     `json:"creator"`
	Topic       string     `json:"topic"`
	Details     string     `json:"details"`
	Description string     `json:"description"`
	Type        string     `json:"type"`
	Tags        []string   `json:"tags"`
	Date        *time.Time `json:"date"`
	Managers    []string   `json:"managers"`
	Followers   []string   `json:"followers"`
}

type UpdateTaskInput struct {
	ID   string     `json:"id"`
	Text string     `json:"text"`
	Date *time.Time `json:"date"`
}
