// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string               `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Category             string               `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	ContentText          string               `protobuf:"bytes,5,opt,name=contentText,proto3" json:"contentText,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Anonymous            bool                 `protobuf:"varint,7,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	Latitude             float64              `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64              `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	ContentPhoto         *Image               `protobuf:"bytes,11,opt,name=contentPhoto,proto3" json:"contentPhoto,omitempty"`
	ContentFile          *File                `protobuf:"bytes,12,opt,name=contentFile,proto3" json:"contentFile,omitempty"`
	Likes                []string             `protobuf:"bytes,13,rep,name=likes,proto3" json:"likes,omitempty"`
	Agreements           []string             `protobuf:"bytes,14,rep,name=agreements,proto3" json:"agreements,omitempty"`
	Followers            []string             `protobuf:"bytes,15,rep,name=followers,proto3" json:"followers,omitempty"`
	Comments             []string             `protobuf:"bytes,16,rep,name=comments,proto3" json:"comments,omitempty"`
	Share                []string             `protobuf:"bytes,17,rep,name=share,proto3" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Post) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Post) GetContentText() string {
	if m != nil {
		return m.ContentText
	}
	return ""
}

func (m *Post) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Post) GetAnonymous() bool {
	if m != nil {
		return m.Anonymous
	}
	return false
}

func (m *Post) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Post) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Post) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Post) GetContentPhoto() *Image {
	if m != nil {
		return m.ContentPhoto
	}
	return nil
}

func (m *Post) GetContentFile() *File {
	if m != nil {
		return m.ContentFile
	}
	return nil
}

func (m *Post) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *Post) GetAgreements() []string {
	if m != nil {
		return m.Agreements
	}
	return nil
}

func (m *Post) GetFollowers() []string {
	if m != nil {
		return m.Followers
	}
	return nil
}

func (m *Post) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *Post) GetShare() []string {
	if m != nil {
		return m.Share
	}
	return nil
}

type Image struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Width                int32    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type File struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Width                int32    `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *File) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Comment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Comment) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Share struct {
	Party                string   `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Share) Reset()         { *m = Share{} }
func (m *Share) String() string { return proto.CompactTextString(m) }
func (*Share) ProtoMessage()    {}
func (*Share) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *Share) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Share.Unmarshal(m, b)
}
func (m *Share) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Share.Marshal(b, m, deterministic)
}
func (m *Share) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Share.Merge(m, src)
}
func (m *Share) XXX_Size() int {
	return xxx_messageInfo_Share.Size(m)
}
func (m *Share) XXX_DiscardUnknown() {
	xxx_messageInfo_Share.DiscardUnknown(m)
}

var xxx_messageInfo_Share proto.InternalMessageInfo

func (m *Share) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

type PostPostRequest struct {
	Author               string               `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Category             string               `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ContentText          string               `protobuf:"bytes,4,opt,name=contentText,proto3" json:"contentText,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Anonymous            bool                 `protobuf:"varint,6,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	Latitude             float64              `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64              `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,9,opt,name=time,proto3" json:"time,omitempty"`
	ContentPhoto         *Image               `protobuf:"bytes,10,opt,name=contentPhoto,proto3" json:"contentPhoto,omitempty"`
	ContentFile          *File                `protobuf:"bytes,11,opt,name=contentFile,proto3" json:"contentFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostPostRequest) Reset()         { *m = PostPostRequest{} }
func (m *PostPostRequest) String() string { return proto.CompactTextString(m) }
func (*PostPostRequest) ProtoMessage()    {}
func (*PostPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *PostPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostPostRequest.Unmarshal(m, b)
}
func (m *PostPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostPostRequest.Marshal(b, m, deterministic)
}
func (m *PostPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostPostRequest.Merge(m, src)
}
func (m *PostPostRequest) XXX_Size() int {
	return xxx_messageInfo_PostPostRequest.Size(m)
}
func (m *PostPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostPostRequest proto.InternalMessageInfo

func (m *PostPostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PostPostRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PostPostRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PostPostRequest) GetContentText() string {
	if m != nil {
		return m.ContentText
	}
	return ""
}

func (m *PostPostRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PostPostRequest) GetAnonymous() bool {
	if m != nil {
		return m.Anonymous
	}
	return false
}

func (m *PostPostRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PostPostRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PostPostRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PostPostRequest) GetContentPhoto() *Image {
	if m != nil {
		return m.ContentPhoto
	}
	return nil
}

func (m *PostPostRequest) GetContentFile() *File {
	if m != nil {
		return m.ContentFile
	}
	return nil
}

type PostPostResponse struct {
	Post                 string   `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostPostResponse) Reset()         { *m = PostPostResponse{} }
func (m *PostPostResponse) String() string { return proto.CompactTextString(m) }
func (*PostPostResponse) ProtoMessage()    {}
func (*PostPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *PostPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostPostResponse.Unmarshal(m, b)
}
func (m *PostPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostPostResponse.Marshal(b, m, deterministic)
}
func (m *PostPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostPostResponse.Merge(m, src)
}
func (m *PostPostResponse) XXX_Size() int {
	return xxx_messageInfo_PostPostResponse.Size(m)
}
func (m *PostPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostPostResponse proto.InternalMessageInfo

func (m *PostPostResponse) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type GetPostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPostRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type GetMultiplePostsRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultiplePostsRequest) Reset()         { *m = GetMultiplePostsRequest{} }
func (m *GetMultiplePostsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultiplePostsRequest) ProtoMessage()    {}
func (*GetMultiplePostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *GetMultiplePostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultiplePostsRequest.Unmarshal(m, b)
}
func (m *GetMultiplePostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultiplePostsRequest.Marshal(b, m, deterministic)
}
func (m *GetMultiplePostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultiplePostsRequest.Merge(m, src)
}
func (m *GetMultiplePostsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultiplePostsRequest.Size(m)
}
func (m *GetMultiplePostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultiplePostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultiplePostsRequest proto.InternalMessageInfo

func (m *GetMultiplePostsRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetMultiplePostsRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetMultiplePostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultiplePostsResponse) Reset()         { *m = GetMultiplePostsResponse{} }
func (m *GetMultiplePostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultiplePostsResponse) ProtoMessage()    {}
func (*GetMultiplePostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *GetMultiplePostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultiplePostsResponse.Unmarshal(m, b)
}
func (m *GetMultiplePostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultiplePostsResponse.Marshal(b, m, deterministic)
}
func (m *GetMultiplePostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultiplePostsResponse.Merge(m, src)
}
func (m *GetMultiplePostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultiplePostsResponse.Size(m)
}
func (m *GetMultiplePostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultiplePostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultiplePostsResponse proto.InternalMessageInfo

func (m *GetMultiplePostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type PutPostRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author               string               `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Category             string               `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	ContentText          string               `protobuf:"bytes,5,opt,name=contentText,proto3" json:"contentText,omitempty"`
	Type                 string               `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Anonymous            bool                 `protobuf:"varint,7,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	Latitude             float64              `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64              `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,10,opt,name=time,proto3" json:"time,omitempty"`
	ContentPhoto         *Image               `protobuf:"bytes,11,opt,name=contentPhoto,proto3" json:"contentPhoto,omitempty"`
	ContentFile          *File                `protobuf:"bytes,12,opt,name=contentFile,proto3" json:"contentFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutPostRequest) Reset()         { *m = PutPostRequest{} }
func (m *PutPostRequest) String() string { return proto.CompactTextString(m) }
func (*PutPostRequest) ProtoMessage()    {}
func (*PutPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *PutPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPostRequest.Unmarshal(m, b)
}
func (m *PutPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPostRequest.Marshal(b, m, deterministic)
}
func (m *PutPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPostRequest.Merge(m, src)
}
func (m *PutPostRequest) XXX_Size() int {
	return xxx_messageInfo_PutPostRequest.Size(m)
}
func (m *PutPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutPostRequest proto.InternalMessageInfo

func (m *PutPostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutPostRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *PutPostRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PutPostRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PutPostRequest) GetContentText() string {
	if m != nil {
		return m.ContentText
	}
	return ""
}

func (m *PutPostRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutPostRequest) GetAnonymous() bool {
	if m != nil {
		return m.Anonymous
	}
	return false
}

func (m *PutPostRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PutPostRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PutPostRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PutPostRequest) GetContentPhoto() *Image {
	if m != nil {
		return m.ContentPhoto
	}
	return nil
}

func (m *PutPostRequest) GetContentFile() *File {
	if m != nil {
		return m.ContentFile
	}
	return nil
}

type PutPostResponse struct {
	Post                 string   `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutPostResponse) Reset()         { *m = PutPostResponse{} }
func (m *PutPostResponse) String() string { return proto.CompactTextString(m) }
func (*PutPostResponse) ProtoMessage()    {}
func (*PutPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{12}
}

func (m *PutPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutPostResponse.Unmarshal(m, b)
}
func (m *PutPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutPostResponse.Marshal(b, m, deterministic)
}
func (m *PutPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutPostResponse.Merge(m, src)
}
func (m *PutPostResponse) XXX_Size() int {
	return xxx_messageInfo_PutPostResponse.Size(m)
}
func (m *PutPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutPostResponse proto.InternalMessageInfo

func (m *PutPostResponse) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type DeletePostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{13}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{14}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "pb.Post")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*Comment)(nil), "pb.Comment")
	proto.RegisterType((*Share)(nil), "pb.Share")
	proto.RegisterType((*PostPostRequest)(nil), "pb.PostPostRequest")
	proto.RegisterType((*PostPostResponse)(nil), "pb.PostPostResponse")
	proto.RegisterType((*GetPostRequest)(nil), "pb.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "pb.GetPostResponse")
	proto.RegisterType((*GetMultiplePostsRequest)(nil), "pb.GetMultiplePostsRequest")
	proto.RegisterType((*GetMultiplePostsResponse)(nil), "pb.GetMultiplePostsResponse")
	proto.RegisterType((*PutPostRequest)(nil), "pb.PutPostRequest")
	proto.RegisterType((*PutPostResponse)(nil), "pb.PutPostResponse")
	proto.RegisterType((*DeletePostRequest)(nil), "pb.DeletePostRequest")
	proto.RegisterType((*DeletePostResponse)(nil), "pb.DeletePostResponse")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 756 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0xae, 0x63, 0x3b, 0x8f, 0x49, 0x49, 0xda, 0x6d, 0x29, 0xab, 0x50, 0x4a, 0x64, 0x1e, 0x8a,
	0x90, 0x48, 0xa5, 0x82, 0x04, 0x42, 0xe2, 0x80, 0x28, 0x54, 0x3d, 0x20, 0x2a, 0xb7, 0x7f, 0xc0,
	0x49, 0xa6, 0x89, 0x55, 0xc7, 0x6b, 0xec, 0x35, 0x6d, 0x38, 0x81, 0xf8, 0x67, 0xfc, 0x26, 0xee,
	0xa0, 0x1d, 0x3f, 0xe2, 0xa4, 0x49, 0x10, 0x48, 0x88, 0x0b, 0x87, 0x48, 0x3b, 0xaf, 0x9d, 0xd9,
	0x6f, 0xbe, 0x2f, 0x06, 0x08, 0x44, 0x24, 0xbb, 0x41, 0x28, 0xa4, 0x60, 0xa5, 0xa0, 0xd7, 0xba,
	0x3b, 0x14, 0x62, 0xe8, 0xe1, 0x3e, 0x79, 0x7a, 0xf1, 0xf9, 0xbe, 0x74, 0xc7, 0x18, 0x49, 0x67,
	0x1c, 0x24, 0x49, 0xd6, 0x0f, 0x1d, 0x8c, 0x13, 0x11, 0x49, 0xd6, 0x80, 0x92, 0x3b, 0xe0, 0x5a,
	0x5b, 0xeb, 0xd4, 0xec, 0x92, 0x3b, 0x60, 0x3b, 0x50, 0x76, 0x62, 0x39, 0x12, 0x21, 0x2f, 0x91,
	0x2f, 0xb5, 0xd8, 0x36, 0x98, 0x52, 0x04, 0x6e, 0x9f, 0xeb, 0xe4, 0x4e, 0x0c, 0xd6, 0x82, 0x6a,
	0xdf, 0x91, 0x38, 0x14, 0xe1, 0x84, 0x1b, 0x14, 0xc8, 0x6d, 0xd6, 0x86, 0x7a, 0x5f, 0xf8, 0x12,
	0x7d, 0x79, 0x86, 0x57, 0x92, 0x9b, 0x14, 0x2e, 0xba, 0x18, 0x03, 0x43, 0x4e, 0x02, 0xe4, 0x65,
	0x0a, 0xd1, 0x99, 0xed, 0x42, 0xcd, 0xf1, 0x85, 0x3f, 0x19, 0x8b, 0x38, 0xe2, 0x95, 0xb6, 0xd6,
	0xa9, 0xda, 0x53, 0x87, 0xea, 0xe7, 0x39, 0xd2, 0x95, 0xf1, 0x00, 0x79, 0xb5, 0xad, 0x75, 0x34,
	0x3b, 0xb7, 0x55, 0xa5, 0x27, 0xfc, 0x61, 0x12, 0xac, 0x51, 0x70, 0xea, 0x60, 0x5d, 0x30, 0x14,
	0x06, 0x1c, 0xda, 0x5a, 0xa7, 0x7e, 0xd0, 0xea, 0x26, 0x00, 0x75, 0x33, 0x80, 0xba, 0x67, 0x19,
	0x40, 0x36, 0xe5, 0xb1, 0xc7, 0xb0, 0x9e, 0x8e, 0x7a, 0x32, 0x12, 0x52, 0xf0, 0x3a, 0xd5, 0xd5,
	0xba, 0x41, 0xaf, 0x7b, 0x3c, 0x76, 0x86, 0x68, 0xcf, 0x84, 0xd9, 0xa3, 0xfc, 0xb1, 0x6f, 0x5d,
	0x0f, 0xf9, 0x3a, 0x65, 0x57, 0x55, 0xb6, 0xb2, 0xed, 0x62, 0x50, 0x41, 0xe9, 0xb9, 0x17, 0x18,
	0xf1, 0x1b, 0x6d, 0x5d, 0x41, 0x49, 0x06, 0xdb, 0x03, 0x70, 0x86, 0x21, 0xe2, 0x18, 0x7d, 0x19,
	0xf1, 0x06, 0x85, 0x0a, 0x1e, 0xf5, 0xbc, 0x73, 0xe1, 0x79, 0xe2, 0x12, 0xc3, 0x88, 0x37, 0x29,
	0x3c, 0x75, 0xd0, 0x22, 0xc4, 0x38, 0xa9, 0xdd, 0xa0, 0x60, 0x6e, 0xab, 0x7e, 0xd1, 0xc8, 0x09,
	0x91, 0x6f, 0x26, 0xfd, 0xc8, 0xb0, 0xbe, 0x68, 0x60, 0xd2, 0x4b, 0xae, 0x51, 0x80, 0x81, 0xe1,
	0x3b, 0x63, 0x4c, 0x09, 0x40, 0xe7, 0x7c, 0x55, 0x7a, 0x61, 0x55, 0x0c, 0x8c, 0xc8, 0xfd, 0x84,
	0xb4, 0x78, 0xdd, 0xa6, 0xb3, 0xea, 0x75, 0xe9, 0x0e, 0xe4, 0x88, 0xd6, 0x6d, 0xda, 0x89, 0xa1,
	0x48, 0x35, 0x42, 0x77, 0x38, 0x92, 0xb4, 0x6a, 0xd3, 0x4e, 0x2d, 0xeb, 0xb3, 0x06, 0x06, 0x41,
	0xf2, 0xef, 0x46, 0x78, 0x03, 0x95, 0xd7, 0x09, 0x50, 0x8b, 0xa4, 0x10, 0x47, 0x18, 0x1e, 0x1f,
	0x66, 0x52, 0x48, 0x2c, 0x1a, 0x44, 0x31, 0x3a, 0x1b, 0x04, 0xaf, 0xa4, 0x75, 0x07, 0xcc, 0x53,
	0x05, 0xab, 0xea, 0x1e, 0x38, 0xa1, 0x9c, 0xa4, 0xf7, 0x24, 0x86, 0xf5, 0xbd, 0x04, 0x4d, 0x25,
	0x37, 0xf5, 0xb3, 0xf1, 0x43, 0x8c, 0x91, 0x2c, 0x28, 0x4d, 0x5b, 0xac, 0xb4, 0xd2, 0x32, 0xa5,
	0xe9, 0xab, 0x95, 0x66, 0x2c, 0x57, 0x9a, 0xb9, 0x4c, 0x69, 0xe5, 0x55, 0x4a, 0xab, 0xac, 0x52,
	0x5a, 0x75, 0x99, 0xd2, 0x6a, 0x7f, 0xa8, 0x34, 0xf8, 0x2d, 0xa5, 0xd5, 0x57, 0x28, 0xcd, 0x7a,
	0x08, 0x1b, 0x53, 0xd4, 0xa3, 0x40, 0xf8, 0x11, 0x51, 0x46, 0xfd, 0x59, 0xa6, 0xa0, 0xd3, 0xd9,
	0x7a, 0x0e, 0x8d, 0x23, 0x9c, 0x59, 0xce, 0x6a, 0x2e, 0x18, 0x19, 0x17, 0xac, 0x7d, 0x68, 0xe6,
	0x95, 0x69, 0x83, 0xdd, 0x42, 0x83, 0x74, 0x32, 0x8a, 0x27, 0xad, 0x5e, 0xc1, 0xad, 0x23, 0x94,
	0xef, 0x62, 0x4f, 0xba, 0x81, 0x87, 0x2a, 0x10, 0x65, 0x3d, 0x15, 0x99, 0x2f, 0xdc, 0x80, 0x0a,
	0x0d, 0x9b, 0xce, 0xb4, 0x38, 0xe7, 0x02, 0xd3, 0xae, 0x74, 0xb6, 0x5e, 0x00, 0xbf, 0x7e, 0x45,
	0xda, 0x7c, 0x0f, 0x4c, 0xd5, 0x26, 0xe2, 0x5a, 0x5b, 0x9f, 0xe9, 0x9e, 0xb8, 0xad, 0xaf, 0x3a,
	0x34, 0x4e, 0xe2, 0x5f, 0x3d, 0xf5, 0xff, 0x17, 0xe0, 0xaf, 0x7e, 0x01, 0xac, 0x07, 0xd0, 0xcc,
	0x97, 0xb0, 0x82, 0x96, 0xf7, 0x60, 0xf3, 0x10, 0x3d, 0x94, 0xb8, 0x62, 0x5d, 0xd6, 0x7d, 0x60,
	0xc5, 0xa4, 0xf4, 0xba, 0xb9, 0xac, 0x83, 0x6f, 0x25, 0xa8, 0xab, 0x84, 0x53, 0x0c, 0x3f, 0xba,
	0x7d, 0x64, 0xcf, 0xa0, 0x9a, 0x29, 0x83, 0x6d, 0x65, 0x24, 0x29, 0xb4, 0x69, 0x6d, 0xcf, 0x3a,
	0x93, 0x6b, 0xad, 0x35, 0xf6, 0x14, 0x2a, 0x29, 0xe1, 0x19, 0x53, 0x29, 0xb3, 0xba, 0x69, 0x6d,
	0xcd, 0xf8, 0xf2, 0xaa, 0xf7, 0xb0, 0x31, 0x4f, 0x59, 0x76, 0x3b, 0x4d, 0x5d, 0xa4, 0x85, 0xd6,
	0xee, 0xe2, 0x60, 0x71, 0x8c, 0x14, 0xc1, 0x64, 0x8c, 0x59, 0x4e, 0x27, 0x63, 0xcc, 0x41, 0x6c,
	0xad, 0xb1, 0x97, 0x00, 0x53, 0xac, 0xd8, 0x4d, 0x95, 0x74, 0x0d, 0xe0, 0xd6, 0xce, 0xbc, 0x3b,
	0x2b, 0xef, 0x95, 0x89, 0x2b, 0x4f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x92, 0x00, 0x9d, 0xea,
	0x6e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	PostPost(ctx context.Context, in *PostPostRequest, opts ...grpc.CallOption) (*PostPostResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	GetMultiplePosts(ctx context.Context, in *GetMultiplePostsRequest, opts ...grpc.CallOption) (*GetMultiplePostsResponse, error)
	PutPost(ctx context.Context, in *PutPostRequest, opts ...grpc.CallOption) (*PutPostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) PostPost(ctx context.Context, in *PostPostRequest, opts ...grpc.CallOption) (*PostPostResponse, error) {
	out := new(PostPostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/PostPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetMultiplePosts(ctx context.Context, in *GetMultiplePostsRequest, opts ...grpc.CallOption) (*GetMultiplePostsResponse, error) {
	out := new(GetMultiplePostsResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/GetMultiplePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) PutPost(ctx context.Context, in *PutPostRequest, opts ...grpc.CallOption) (*PutPostResponse, error) {
	out := new(PutPostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/PutPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/pb.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	PostPost(context.Context, *PostPostRequest) (*PostPostResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	GetMultiplePosts(context.Context, *GetMultiplePostsRequest) (*GetMultiplePostsResponse, error)
	PutPost(context.Context, *PutPostRequest) (*PutPostResponse, error)
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) PostPost(ctx context.Context, req *PostPostRequest) (*PostPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostPost not implemented")
}
func (*UnimplementedPostServiceServer) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostServiceServer) GetMultiplePosts(ctx context.Context, req *GetMultiplePostsRequest) (*GetMultiplePostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultiplePosts not implemented")
}
func (*UnimplementedPostServiceServer) PutPost(ctx context.Context, req *PutPostRequest) (*PutPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPost not implemented")
}
func (*UnimplementedPostServiceServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_PostPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).PostPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/PostPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).PostPost(ctx, req.(*PostPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetMultiplePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultiplePostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetMultiplePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/GetMultiplePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetMultiplePosts(ctx, req.(*GetMultiplePostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_PutPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).PutPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/PutPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).PutPost(ctx, req.(*PutPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostPost",
			Handler:    _PostService_PostPost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "GetMultiplePosts",
			Handler:    _PostService_GetMultiplePosts_Handler,
		},
		{
			MethodName: "PutPost",
			Handler:    _PostService_PutPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
