// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reaction.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Reaction struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonID             string               `protobuf:"bytes,2,opt,name=personID,proto3" json:"personID,omitempty"`
	Managers             []string             `protobuf:"bytes,3,rep,name=managers,proto3" json:"managers,omitempty"`
	Details              string               `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Similarities         []string             `protobuf:"bytes,7,rep,name=similarities,proto3" json:"similarities,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Reaction) Reset()         { *m = Reaction{} }
func (m *Reaction) String() string { return proto.CompactTextString(m) }
func (*Reaction) ProtoMessage()    {}
func (*Reaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{0}
}

func (m *Reaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reaction.Unmarshal(m, b)
}
func (m *Reaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reaction.Marshal(b, m, deterministic)
}
func (m *Reaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reaction.Merge(m, src)
}
func (m *Reaction) XXX_Size() int {
	return xxx_messageInfo_Reaction.Size(m)
}
func (m *Reaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Reaction.DiscardUnknown(m)
}

var xxx_messageInfo_Reaction proto.InternalMessageInfo

func (m *Reaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reaction) GetPersonID() string {
	if m != nil {
		return m.PersonID
	}
	return ""
}

func (m *Reaction) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

func (m *Reaction) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Reaction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Reaction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Reaction) GetSimilarities() []string {
	if m != nil {
		return m.Similarities
	}
	return nil
}

func (m *Reaction) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PostReactionRequest struct {
	PersonID             string               `protobuf:"bytes,1,opt,name=personID,proto3" json:"personID,omitempty"`
	Managers             []string             `protobuf:"bytes,2,rep,name=managers,proto3" json:"managers,omitempty"`
	Details              string               `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Similarities         []string             `protobuf:"bytes,6,rep,name=similarities,proto3" json:"similarities,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostReactionRequest) Reset()         { *m = PostReactionRequest{} }
func (m *PostReactionRequest) String() string { return proto.CompactTextString(m) }
func (*PostReactionRequest) ProtoMessage()    {}
func (*PostReactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{1}
}

func (m *PostReactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReactionRequest.Unmarshal(m, b)
}
func (m *PostReactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReactionRequest.Marshal(b, m, deterministic)
}
func (m *PostReactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReactionRequest.Merge(m, src)
}
func (m *PostReactionRequest) XXX_Size() int {
	return xxx_messageInfo_PostReactionRequest.Size(m)
}
func (m *PostReactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostReactionRequest proto.InternalMessageInfo

func (m *PostReactionRequest) GetPersonID() string {
	if m != nil {
		return m.PersonID
	}
	return ""
}

func (m *PostReactionRequest) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

func (m *PostReactionRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *PostReactionRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PostReactionRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostReactionRequest) GetSimilarities() []string {
	if m != nil {
		return m.Similarities
	}
	return nil
}

func (m *PostReactionRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PostReactionResponse struct {
	Reaction             string   `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostReactionResponse) Reset()         { *m = PostReactionResponse{} }
func (m *PostReactionResponse) String() string { return proto.CompactTextString(m) }
func (*PostReactionResponse) ProtoMessage()    {}
func (*PostReactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{2}
}

func (m *PostReactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostReactionResponse.Unmarshal(m, b)
}
func (m *PostReactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostReactionResponse.Marshal(b, m, deterministic)
}
func (m *PostReactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostReactionResponse.Merge(m, src)
}
func (m *PostReactionResponse) XXX_Size() int {
	return xxx_messageInfo_PostReactionResponse.Size(m)
}
func (m *PostReactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostReactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostReactionResponse proto.InternalMessageInfo

func (m *PostReactionResponse) GetReaction() string {
	if m != nil {
		return m.Reaction
	}
	return ""
}

type GetReactionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReactionRequest) Reset()         { *m = GetReactionRequest{} }
func (m *GetReactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetReactionRequest) ProtoMessage()    {}
func (*GetReactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{3}
}

func (m *GetReactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReactionRequest.Unmarshal(m, b)
}
func (m *GetReactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReactionRequest.Marshal(b, m, deterministic)
}
func (m *GetReactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReactionRequest.Merge(m, src)
}
func (m *GetReactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetReactionRequest.Size(m)
}
func (m *GetReactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReactionRequest proto.InternalMessageInfo

func (m *GetReactionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetReactionRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetReactionResponse struct {
	Reaction             *Reaction `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReactionResponse) Reset()         { *m = GetReactionResponse{} }
func (m *GetReactionResponse) String() string { return proto.CompactTextString(m) }
func (*GetReactionResponse) ProtoMessage()    {}
func (*GetReactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{4}
}

func (m *GetReactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReactionResponse.Unmarshal(m, b)
}
func (m *GetReactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReactionResponse.Marshal(b, m, deterministic)
}
func (m *GetReactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReactionResponse.Merge(m, src)
}
func (m *GetReactionResponse) XXX_Size() int {
	return xxx_messageInfo_GetReactionResponse.Size(m)
}
func (m *GetReactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReactionResponse proto.InternalMessageInfo

func (m *GetReactionResponse) GetReaction() *Reaction {
	if m != nil {
		return m.Reaction
	}
	return nil
}

type GetMultipleReactionesRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleReactionesRequest) Reset()         { *m = GetMultipleReactionesRequest{} }
func (m *GetMultipleReactionesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleReactionesRequest) ProtoMessage()    {}
func (*GetMultipleReactionesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{5}
}

func (m *GetMultipleReactionesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleReactionesRequest.Unmarshal(m, b)
}
func (m *GetMultipleReactionesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleReactionesRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleReactionesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleReactionesRequest.Merge(m, src)
}
func (m *GetMultipleReactionesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleReactionesRequest.Size(m)
}
func (m *GetMultipleReactionesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleReactionesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleReactionesRequest proto.InternalMessageInfo

func (m *GetMultipleReactionesRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetMultipleReactionesRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetMultipleReactionesResponse struct {
	Reactiones           []*Reaction `protobuf:"bytes,1,rep,name=reactiones,proto3" json:"reactiones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMultipleReactionesResponse) Reset()         { *m = GetMultipleReactionesResponse{} }
func (m *GetMultipleReactionesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleReactionesResponse) ProtoMessage()    {}
func (*GetMultipleReactionesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{6}
}

func (m *GetMultipleReactionesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleReactionesResponse.Unmarshal(m, b)
}
func (m *GetMultipleReactionesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleReactionesResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleReactionesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleReactionesResponse.Merge(m, src)
}
func (m *GetMultipleReactionesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleReactionesResponse.Size(m)
}
func (m *GetMultipleReactionesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleReactionesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleReactionesResponse proto.InternalMessageInfo

func (m *GetMultipleReactionesResponse) GetReactiones() []*Reaction {
	if m != nil {
		return m.Reactiones
	}
	return nil
}

type PutReactionRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PersonID             string               `protobuf:"bytes,2,opt,name=personID,proto3" json:"personID,omitempty"`
	Managers             []string             `protobuf:"bytes,3,rep,name=managers,proto3" json:"managers,omitempty"`
	Details              string               `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Similarities         []string             `protobuf:"bytes,7,rep,name=similarities,proto3" json:"similarities,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutReactionRequest) Reset()         { *m = PutReactionRequest{} }
func (m *PutReactionRequest) String() string { return proto.CompactTextString(m) }
func (*PutReactionRequest) ProtoMessage()    {}
func (*PutReactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{7}
}

func (m *PutReactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReactionRequest.Unmarshal(m, b)
}
func (m *PutReactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReactionRequest.Marshal(b, m, deterministic)
}
func (m *PutReactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReactionRequest.Merge(m, src)
}
func (m *PutReactionRequest) XXX_Size() int {
	return xxx_messageInfo_PutReactionRequest.Size(m)
}
func (m *PutReactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutReactionRequest proto.InternalMessageInfo

func (m *PutReactionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutReactionRequest) GetPersonID() string {
	if m != nil {
		return m.PersonID
	}
	return ""
}

func (m *PutReactionRequest) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

func (m *PutReactionRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *PutReactionRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutReactionRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PutReactionRequest) GetSimilarities() []string {
	if m != nil {
		return m.Similarities
	}
	return nil
}

func (m *PutReactionRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PutReactionResponse struct {
	Reaction             string   `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutReactionResponse) Reset()         { *m = PutReactionResponse{} }
func (m *PutReactionResponse) String() string { return proto.CompactTextString(m) }
func (*PutReactionResponse) ProtoMessage()    {}
func (*PutReactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{8}
}

func (m *PutReactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutReactionResponse.Unmarshal(m, b)
}
func (m *PutReactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutReactionResponse.Marshal(b, m, deterministic)
}
func (m *PutReactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutReactionResponse.Merge(m, src)
}
func (m *PutReactionResponse) XXX_Size() int {
	return xxx_messageInfo_PutReactionResponse.Size(m)
}
func (m *PutReactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutReactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutReactionResponse proto.InternalMessageInfo

func (m *PutReactionResponse) GetReaction() string {
	if m != nil {
		return m.Reaction
	}
	return ""
}

type DeleteReactionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReactionRequest) Reset()         { *m = DeleteReactionRequest{} }
func (m *DeleteReactionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReactionRequest) ProtoMessage()    {}
func (*DeleteReactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{9}
}

func (m *DeleteReactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReactionRequest.Unmarshal(m, b)
}
func (m *DeleteReactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReactionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReactionRequest.Merge(m, src)
}
func (m *DeleteReactionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReactionRequest.Size(m)
}
func (m *DeleteReactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReactionRequest proto.InternalMessageInfo

func (m *DeleteReactionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteReactionResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReactionResponse) Reset()         { *m = DeleteReactionResponse{} }
func (m *DeleteReactionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReactionResponse) ProtoMessage()    {}
func (*DeleteReactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c69bb78c0ce7b5ac, []int{10}
}

func (m *DeleteReactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReactionResponse.Unmarshal(m, b)
}
func (m *DeleteReactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReactionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReactionResponse.Merge(m, src)
}
func (m *DeleteReactionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReactionResponse.Size(m)
}
func (m *DeleteReactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReactionResponse proto.InternalMessageInfo

func (m *DeleteReactionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Reaction)(nil), "pb.Reaction")
	proto.RegisterType((*PostReactionRequest)(nil), "pb.PostReactionRequest")
	proto.RegisterType((*PostReactionResponse)(nil), "pb.PostReactionResponse")
	proto.RegisterType((*GetReactionRequest)(nil), "pb.GetReactionRequest")
	proto.RegisterType((*GetReactionResponse)(nil), "pb.GetReactionResponse")
	proto.RegisterType((*GetMultipleReactionesRequest)(nil), "pb.GetMultipleReactionesRequest")
	proto.RegisterType((*GetMultipleReactionesResponse)(nil), "pb.GetMultipleReactionesResponse")
	proto.RegisterType((*PutReactionRequest)(nil), "pb.PutReactionRequest")
	proto.RegisterType((*PutReactionResponse)(nil), "pb.PutReactionResponse")
	proto.RegisterType((*DeleteReactionRequest)(nil), "pb.DeleteReactionRequest")
	proto.RegisterType((*DeleteReactionResponse)(nil), "pb.DeleteReactionResponse")
}

func init() { proto.RegisterFile("reaction.proto", fileDescriptor_c69bb78c0ce7b5ac) }

var fileDescriptor_c69bb78c0ce7b5ac = []byte{
	// 520 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0x1d, 0x37, 0x09, 0x93, 0x28, 0x48, 0x13, 0x9a, 0x2e, 0x16, 0x08, 0xb3, 0x17, 0x72,
	0x40, 0xae, 0x08, 0x57, 0x24, 0x90, 0xa8, 0xa8, 0x7a, 0xa8, 0x54, 0x19, 0xce, 0x48, 0x4e, 0x32,
	0x44, 0xab, 0x3a, 0xf1, 0xe2, 0xdd, 0x20, 0x71, 0xe3, 0xc2, 0x07, 0x73, 0xe1, 0x8c, 0xbc, 0xf1,
	0x06, 0x3b, 0x76, 0x92, 0x9e, 0x7b, 0xdb, 0x99, 0x79, 0x3b, 0xf3, 0xde, 0xec, 0x5b, 0x18, 0x64,
	0x14, 0xcf, 0xb4, 0x48, 0x57, 0xa1, 0xcc, 0x52, 0x9d, 0xa2, 0x2b, 0xa7, 0xfe, 0x8b, 0x45, 0x9a,
	0x2e, 0x12, 0xba, 0x30, 0x99, 0xe9, 0xfa, 0xdb, 0x85, 0x16, 0x4b, 0x52, 0x3a, 0x5e, 0xca, 0x0d,
	0x88, 0xff, 0x75, 0xa0, 0x1b, 0x15, 0xf7, 0x70, 0x00, 0xae, 0x98, 0x33, 0x27, 0x70, 0xc6, 0x8f,
	0x22, 0x57, 0xcc, 0xd1, 0x87, 0xae, 0xa4, 0x4c, 0xa5, 0xab, 0xeb, 0x4b, 0xe6, 0x9a, 0xec, 0x36,
	0xce, 0x6b, 0xcb, 0x78, 0x15, 0x2f, 0x28, 0x53, 0xac, 0x15, 0xb4, 0xf2, 0x9a, 0x8d, 0x91, 0x41,
	0x67, 0x4e, 0x3a, 0x16, 0x89, 0x62, 0x9e, 0xb9, 0x66, 0x43, 0x44, 0xf0, 0xf4, 0x4f, 0x49, 0xec,
	0xd4, 0xa4, 0xcd, 0x19, 0x03, 0xe8, 0xcd, 0x49, 0xcd, 0x32, 0x21, 0x73, 0x12, 0xac, 0x6d, 0x4a,
	0xe5, 0x14, 0x72, 0xe8, 0x2b, 0xb1, 0x14, 0x49, 0x9c, 0x09, 0x2d, 0x48, 0xb1, 0x8e, 0x99, 0x57,
	0xc9, 0x61, 0x08, 0x5e, 0xae, 0x8d, 0x75, 0x03, 0x67, 0xdc, 0x9b, 0xf8, 0xe1, 0x46, 0x78, 0x68,
	0x85, 0x87, 0x5f, 0xac, 0xf0, 0xc8, 0xe0, 0xf8, 0x1f, 0x07, 0x86, 0xb7, 0xa9, 0xd2, 0x56, 0x7c,
	0x44, 0xdf, 0xd7, 0xa4, 0x74, 0x45, 0xb3, 0x73, 0x40, 0xb3, 0xbb, 0x5f, 0x73, 0xab, 0x59, 0xb3,
	0xb7, 0x5f, 0xf3, 0xe9, 0x71, 0xcd, 0xed, 0x03, 0x9a, 0x3b, 0xf7, 0xd4, 0x3c, 0x81, 0x27, 0x55,
	0xc9, 0x4a, 0xa6, 0x2b, 0x45, 0xb9, 0x2e, 0xeb, 0x1d, 0xab, 0xd9, 0xc6, 0xfc, 0x1d, 0xe0, 0x15,
	0xd5, 0xb6, 0xb4, 0xeb, 0x94, 0x11, 0xb4, 0xd7, 0x8a, 0xb2, 0xc2, 0x27, 0x5e, 0x54, 0x44, 0xfc,
	0x3d, 0x0c, 0x2b, 0xb7, 0x8b, 0x81, 0xe3, 0x9d, 0x81, 0xbd, 0x49, 0x3f, 0x94, 0xd3, 0x70, 0x8b,
	0xfb, 0x3f, 0xfe, 0x13, 0x3c, 0xbb, 0x22, 0x7d, 0xb3, 0x4e, 0xb4, 0x90, 0x09, 0x59, 0x00, 0x29,
	0x4b, 0x04, 0xc1, 0x53, 0x77, 0x42, 0x9a, 0x2e, 0x5e, 0x64, 0xce, 0x66, 0xe1, 0xf1, 0x1d, 0x15,
	0x54, 0xcc, 0x99, 0xdf, 0xc0, 0xf3, 0x3d, 0x7d, 0x0a, 0x4a, 0xaf, 0x01, 0xb2, 0x6d, 0x96, 0x39,
	0x41, 0xab, 0x46, 0xaa, 0x54, 0xe7, 0xbf, 0x5c, 0xc0, 0xdb, 0xf5, 0xd1, 0xb5, 0x3c, 0xe4, 0x0f,
	0xf4, 0x06, 0x86, 0x95, 0x0d, 0xdc, 0xc3, 0x4b, 0xaf, 0xe0, 0xec, 0x92, 0x12, 0xd2, 0x74, 0x64,
	0x6f, 0x7c, 0x0c, 0xa3, 0x5d, 0x60, 0xd1, 0x7e, 0x07, 0x39, 0xf9, 0xdd, 0x82, 0xc7, 0x16, 0xf4,
	0x99, 0xb2, 0x1f, 0x62, 0x46, 0xf8, 0x11, 0xfa, 0x65, 0x9b, 0xe3, 0x79, 0xfe, 0x8c, 0x0d, 0x7f,
	0xdd, 0x67, 0xf5, 0xc2, 0x66, 0x0c, 0x3f, 0xc1, 0x0f, 0xd0, 0x2b, 0x39, 0x17, 0x47, 0x39, 0xb4,
	0xfe, 0x11, 0xfc, 0xf3, 0x5a, 0x7e, 0xdb, 0xe1, 0x2b, 0x9c, 0x35, 0x5a, 0x0e, 0x83, 0xe2, 0xce,
	0x5e, 0x57, 0xfb, 0x2f, 0x0f, 0x20, 0xca, 0x0c, 0x4b, 0x0f, 0xb0, 0x61, 0x58, 0xf7, 0xe4, 0x86,
	0x61, 0xc3, 0x4b, 0xf1, 0x13, 0xbc, 0x86, 0x41, 0x75, 0xcd, 0xf8, 0x34, 0x07, 0x37, 0xbe, 0x91,
	0xef, 0x37, 0x95, 0x6c, 0xab, 0x69, 0xdb, 0xf8, 0xe4, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x2a, 0x5f, 0xd0, 0x85, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReactionServiceClient is the client API for ReactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReactionServiceClient interface {
	PostReaction(ctx context.Context, in *PostReactionRequest, opts ...grpc.CallOption) (*PostReactionResponse, error)
	GetReaction(ctx context.Context, in *GetReactionRequest, opts ...grpc.CallOption) (*GetReactionResponse, error)
	GetMultipleReactiones(ctx context.Context, in *GetMultipleReactionesRequest, opts ...grpc.CallOption) (*GetMultipleReactionesResponse, error)
	PutReaction(ctx context.Context, in *PutReactionRequest, opts ...grpc.CallOption) (*PutReactionResponse, error)
	DeleteReaction(ctx context.Context, in *DeleteReactionRequest, opts ...grpc.CallOption) (*DeleteReactionResponse, error)
}

type reactionServiceClient struct {
	cc *grpc.ClientConn
}

func NewReactionServiceClient(cc *grpc.ClientConn) ReactionServiceClient {
	return &reactionServiceClient{cc}
}

func (c *reactionServiceClient) PostReaction(ctx context.Context, in *PostReactionRequest, opts ...grpc.CallOption) (*PostReactionResponse, error) {
	out := new(PostReactionResponse)
	err := c.cc.Invoke(ctx, "/pb.ReactionService/PostReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) GetReaction(ctx context.Context, in *GetReactionRequest, opts ...grpc.CallOption) (*GetReactionResponse, error) {
	out := new(GetReactionResponse)
	err := c.cc.Invoke(ctx, "/pb.ReactionService/GetReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) GetMultipleReactiones(ctx context.Context, in *GetMultipleReactionesRequest, opts ...grpc.CallOption) (*GetMultipleReactionesResponse, error) {
	out := new(GetMultipleReactionesResponse)
	err := c.cc.Invoke(ctx, "/pb.ReactionService/GetMultipleReactiones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) PutReaction(ctx context.Context, in *PutReactionRequest, opts ...grpc.CallOption) (*PutReactionResponse, error) {
	out := new(PutReactionResponse)
	err := c.cc.Invoke(ctx, "/pb.ReactionService/PutReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reactionServiceClient) DeleteReaction(ctx context.Context, in *DeleteReactionRequest, opts ...grpc.CallOption) (*DeleteReactionResponse, error) {
	out := new(DeleteReactionResponse)
	err := c.cc.Invoke(ctx, "/pb.ReactionService/DeleteReaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactionServiceServer is the server API for ReactionService service.
type ReactionServiceServer interface {
	PostReaction(context.Context, *PostReactionRequest) (*PostReactionResponse, error)
	GetReaction(context.Context, *GetReactionRequest) (*GetReactionResponse, error)
	GetMultipleReactiones(context.Context, *GetMultipleReactionesRequest) (*GetMultipleReactionesResponse, error)
	PutReaction(context.Context, *PutReactionRequest) (*PutReactionResponse, error)
	DeleteReaction(context.Context, *DeleteReactionRequest) (*DeleteReactionResponse, error)
}

// UnimplementedReactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReactionServiceServer struct {
}

func (*UnimplementedReactionServiceServer) PostReaction(ctx context.Context, req *PostReactionRequest) (*PostReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostReaction not implemented")
}
func (*UnimplementedReactionServiceServer) GetReaction(ctx context.Context, req *GetReactionRequest) (*GetReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReaction not implemented")
}
func (*UnimplementedReactionServiceServer) GetMultipleReactiones(ctx context.Context, req *GetMultipleReactionesRequest) (*GetMultipleReactionesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleReactiones not implemented")
}
func (*UnimplementedReactionServiceServer) PutReaction(ctx context.Context, req *PutReactionRequest) (*PutReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutReaction not implemented")
}
func (*UnimplementedReactionServiceServer) DeleteReaction(ctx context.Context, req *DeleteReactionRequest) (*DeleteReactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReaction not implemented")
}

func RegisterReactionServiceServer(s *grpc.Server, srv ReactionServiceServer) {
	s.RegisterService(&_ReactionService_serviceDesc, srv)
}

func _ReactionService_PostReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).PostReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReactionService/PostReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).PostReaction(ctx, req.(*PostReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_GetReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).GetReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReactionService/GetReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).GetReaction(ctx, req.(*GetReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_GetMultipleReactiones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleReactionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).GetMultipleReactiones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReactionService/GetMultipleReactiones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).GetMultipleReactiones(ctx, req.(*GetMultipleReactionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_PutReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).PutReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReactionService/PutReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).PutReaction(ctx, req.(*PutReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReactionService_DeleteReaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServiceServer).DeleteReaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ReactionService/DeleteReaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServiceServer).DeleteReaction(ctx, req.(*DeleteReactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ReactionService",
	HandlerType: (*ReactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostReaction",
			Handler:    _ReactionService_PostReaction_Handler,
		},
		{
			MethodName: "GetReaction",
			Handler:    _ReactionService_GetReaction_Handler,
		},
		{
			MethodName: "GetMultipleReactiones",
			Handler:    _ReactionService_GetMultipleReactiones_Handler,
		},
		{
			MethodName: "PutReaction",
			Handler:    _ReactionService_PutReaction_Handler,
		},
		{
			MethodName: "DeleteReaction",
			Handler:    _ReactionService_DeleteReaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reaction.proto",
}
