// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               string               `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Details              string               `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TotalPrice           float64              `protobuf:"fixed64,6,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	OrderedProducts      []*OrderedProduct    `protobuf:"bytes,7,rep,name=orderedProducts,proto3" json:"orderedProducts,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Order) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetTotalPrice() float64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetOrderedProducts() []*OrderedProduct {
	if m != nil {
		return m.OrderedProducts
	}
	return nil
}

func (m *Order) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

type OrderedProduct struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             uint32   `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderedProduct) Reset()         { *m = OrderedProduct{} }
func (m *OrderedProduct) String() string { return proto.CompactTextString(m) }
func (*OrderedProduct) ProtoMessage()    {}
func (*OrderedProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderedProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderedProduct.Unmarshal(m, b)
}
func (m *OrderedProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderedProduct.Marshal(b, m, deterministic)
}
func (m *OrderedProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderedProduct.Merge(m, src)
}
func (m *OrderedProduct) XXX_Size() int {
	return xxx_messageInfo_OrderedProduct.Size(m)
}
func (m *OrderedProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderedProduct.DiscardUnknown(m)
}

var xxx_messageInfo_OrderedProduct proto.InternalMessageInfo

func (m *OrderedProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderedProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderedProduct) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *OrderedProduct) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderedProduct) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type PostOrderRequest struct {
	UserID               string                           `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Products             []*PostOrderRequest_OrderProduct `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *PostOrderRequest) Reset()         { *m = PostOrderRequest{} }
func (m *PostOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PostOrderRequest) ProtoMessage()    {}
func (*PostOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *PostOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderRequest.Unmarshal(m, b)
}
func (m *PostOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderRequest.Marshal(b, m, deterministic)
}
func (m *PostOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderRequest.Merge(m, src)
}
func (m *PostOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PostOrderRequest.Size(m)
}
func (m *PostOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderRequest proto.InternalMessageInfo

func (m *PostOrderRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PostOrderRequest) GetProducts() []*PostOrderRequest_OrderProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

type PostOrderRequest_OrderProduct struct {
	ProductId            string   `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOrderRequest_OrderProduct) Reset()         { *m = PostOrderRequest_OrderProduct{} }
func (m *PostOrderRequest_OrderProduct) String() string { return proto.CompactTextString(m) }
func (*PostOrderRequest_OrderProduct) ProtoMessage()    {}
func (*PostOrderRequest_OrderProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2, 0}
}

func (m *PostOrderRequest_OrderProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderRequest_OrderProduct.Unmarshal(m, b)
}
func (m *PostOrderRequest_OrderProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderRequest_OrderProduct.Marshal(b, m, deterministic)
}
func (m *PostOrderRequest_OrderProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderRequest_OrderProduct.Merge(m, src)
}
func (m *PostOrderRequest_OrderProduct) XXX_Size() int {
	return xxx_messageInfo_PostOrderRequest_OrderProduct.Size(m)
}
func (m *PostOrderRequest_OrderProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderRequest_OrderProduct.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderRequest_OrderProduct proto.InternalMessageInfo

func (m *PostOrderRequest_OrderProduct) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *PostOrderRequest_OrderProduct) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type PostOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostOrderResponse) Reset()         { *m = PostOrderResponse{} }
func (m *PostOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PostOrderResponse) ProtoMessage()    {}
func (*PostOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *PostOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostOrderResponse.Unmarshal(m, b)
}
func (m *PostOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostOrderResponse.Marshal(b, m, deterministic)
}
func (m *PostOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostOrderResponse.Merge(m, src)
}
func (m *PostOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PostOrderResponse.Size(m)
}
func (m *PostOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostOrderResponse proto.InternalMessageInfo

func (m *PostOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrderRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetMultipleOrdersRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleOrdersRequest) Reset()         { *m = GetMultipleOrdersRequest{} }
func (m *GetMultipleOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleOrdersRequest) ProtoMessage()    {}
func (*GetMultipleOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *GetMultipleOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleOrdersRequest.Unmarshal(m, b)
}
func (m *GetMultipleOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleOrdersRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleOrdersRequest.Merge(m, src)
}
func (m *GetMultipleOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleOrdersRequest.Size(m)
}
func (m *GetMultipleOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleOrdersRequest proto.InternalMessageInfo

func (m *GetMultipleOrdersRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetMultipleOrdersRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *GetMultipleOrdersRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetMultipleOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleOrdersResponse) Reset()         { *m = GetMultipleOrdersResponse{} }
func (m *GetMultipleOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleOrdersResponse) ProtoMessage()    {}
func (*GetMultipleOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *GetMultipleOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleOrdersResponse.Unmarshal(m, b)
}
func (m *GetMultipleOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleOrdersResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleOrdersResponse.Merge(m, src)
}
func (m *GetMultipleOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleOrdersResponse.Size(m)
}
func (m *GetMultipleOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleOrdersResponse proto.InternalMessageInfo

func (m *GetMultipleOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type DeleteOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRequest) Reset()         { *m = DeleteOrderRequest{} }
func (m *DeleteOrderRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRequest) ProtoMessage()    {}
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *DeleteOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRequest.Unmarshal(m, b)
}
func (m *DeleteOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRequest.Merge(m, src)
}
func (m *DeleteOrderRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRequest.Size(m)
}
func (m *DeleteOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRequest proto.InternalMessageInfo

func (m *DeleteOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteOrderResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderResponse) Reset()         { *m = DeleteOrderResponse{} }
func (m *DeleteOrderResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderResponse) ProtoMessage()    {}
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *DeleteOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderResponse.Unmarshal(m, b)
}
func (m *DeleteOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderResponse.Marshal(b, m, deterministic)
}
func (m *DeleteOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderResponse.Merge(m, src)
}
func (m *DeleteOrderResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderResponse.Size(m)
}
func (m *DeleteOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderResponse proto.InternalMessageInfo

func (m *DeleteOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*OrderedProduct)(nil), "pb.OrderedProduct")
	proto.RegisterType((*PostOrderRequest)(nil), "pb.PostOrderRequest")
	proto.RegisterType((*PostOrderRequest_OrderProduct)(nil), "pb.PostOrderRequest.OrderProduct")
	proto.RegisterType((*PostOrderResponse)(nil), "pb.PostOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "pb.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "pb.GetOrderResponse")
	proto.RegisterType((*GetMultipleOrdersRequest)(nil), "pb.GetMultipleOrdersRequest")
	proto.RegisterType((*GetMultipleOrdersResponse)(nil), "pb.GetMultipleOrdersResponse")
	proto.RegisterType((*DeleteOrderRequest)(nil), "pb.DeleteOrderRequest")
	proto.RegisterType((*DeleteOrderResponse)(nil), "pb.DeleteOrderResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0xe3, 0xa4, 0xc9, 0x18, 0xfa, 0x31, 0x2d, 0x65, 0xb1, 0x0a, 0x4d, 0x2d, 0x90,
	0x72, 0x72, 0xa5, 0x14, 0x89, 0x0f, 0x01, 0xe2, 0x50, 0xa9, 0xf4, 0x80, 0x5a, 0x19, 0x4e, 0xdc,
	0x9c, 0x78, 0xa8, 0xac, 0x3a, 0xf1, 0xd6, 0xbb, 0x46, 0xea, 0x1b, 0xf0, 0x06, 0x88, 0xe7, 0xe0,
	0x05, 0x51, 0xc6, 0x1f, 0xb1, 0x9d, 0xb4, 0xe2, 0xb6, 0xfb, 0x9f, 0xef, 0xdf, 0xac, 0x16, 0xec,
	0x24, 0x0d, 0x29, 0xf5, 0x64, 0x9a, 0xe8, 0x04, 0x4d, 0x39, 0x71, 0x0e, 0xaf, 0x92, 0xe4, 0x2a,
	0xa6, 0x63, 0x56, 0x26, 0xd9, 0x8f, 0x63, 0x1d, 0xcd, 0x48, 0xe9, 0x60, 0x26, 0x73, 0x27, 0xf7,
	0xb7, 0x09, 0xdd, 0x8b, 0x45, 0x10, 0x6e, 0x82, 0x19, 0x85, 0xc2, 0x18, 0x1a, 0xa3, 0x81, 0x6f,
	0x46, 0x21, 0xee, 0x43, 0x2f, 0x53, 0x94, 0x9e, 0x9f, 0x0a, 0x93, 0xb5, 0xe2, 0x86, 0x02, 0x36,
	0x42, 0xd2, 0x41, 0x14, 0x2b, 0xd1, 0x61, 0x43, 0x79, 0x45, 0x04, 0x4b, 0xdf, 0x4a, 0x12, 0x16,
	0xcb, 0x7c, 0xc6, 0x21, 0xd8, 0x21, 0xa9, 0x69, 0x1a, 0x49, 0x1d, 0x25, 0x73, 0xd1, 0x65, 0x53,
	0x5d, 0xc2, 0xe7, 0x00, 0x3a, 0xd1, 0x41, 0x7c, 0x99, 0x46, 0x53, 0x12, 0xbd, 0xa1, 0x31, 0x32,
	0xfc, 0x9a, 0x82, 0xef, 0x61, 0x8b, 0xa7, 0xa2, 0xf0, 0x32, 0x4d, 0xc2, 0x6c, 0xaa, 0x95, 0xd8,
	0x18, 0x76, 0x46, 0xf6, 0x18, 0x3d, 0x39, 0xf1, 0x2e, 0x1a, 0x26, 0xbf, 0xed, 0x8a, 0x6f, 0x60,
	0x30, 0x4d, 0x29, 0xd0, 0x14, 0x5e, 0xcc, 0x45, 0x7f, 0x68, 0x8c, 0xec, 0xb1, 0xe3, 0xe5, 0x50,
	0xbc, 0x12, 0x8a, 0xf7, 0xad, 0x84, 0xe2, 0x2f, 0x9d, 0xdd, 0x5f, 0x06, 0x6c, 0x36, 0xb3, 0xaf,
	0x20, 0x42, 0xb0, 0xe6, 0xc1, 0x8c, 0x0a, 0x40, 0x7c, 0x6e, 0x0f, 0xdc, 0x59, 0x1d, 0x78, 0x0f,
	0xba, 0x92, 0x67, 0xb5, 0x78, 0xd6, 0xfc, 0x82, 0x0e, 0xf4, 0x6f, 0xb2, 0x60, 0xae, 0x23, 0x7d,
	0xcb, 0x94, 0x1e, 0xf9, 0xd5, 0xdd, 0xfd, 0x6b, 0xc0, 0xf6, 0x65, 0xa2, 0x34, 0xb7, 0xe3, 0xd3,
	0x4d, 0x46, 0x4a, 0xdf, 0xb9, 0x9f, 0x0f, 0xd0, 0x97, 0x25, 0x28, 0x8b, 0x41, 0x1d, 0x2d, 0x40,
	0xb5, 0xe3, 0x73, 0x72, 0x25, 0xb7, 0x2a, 0xc4, 0xf9, 0x0c, 0x0f, 0xeb, 0x16, 0x3c, 0x80, 0x41,
	0x61, 0x3b, 0x0f, 0x8b, 0x4a, 0x4b, 0xa1, 0xd1, 0x75, 0xa7, 0xd5, 0xf5, 0x2b, 0xd8, 0xa9, 0x15,
	0x55, 0x32, 0x99, 0x2b, 0xc2, 0x43, 0xe8, 0xf2, 0x8a, 0x98, 0xa2, 0x3d, 0x1e, 0x54, 0x3b, 0xf4,
	0x73, 0xdd, 0x7d, 0x0b, 0x5b, 0x67, 0xd4, 0x9c, 0xf4, 0xfe, 0x97, 0x69, 0x95, 0x93, 0xbb, 0x27,
	0xb0, 0xbd, 0x0c, 0xfd, 0xdf, 0x7a, 0xdf, 0x41, 0x9c, 0x91, 0xfe, 0x92, 0xc5, 0x3a, 0x92, 0x31,
	0xb1, 0x49, 0x95, 0x85, 0x11, 0x2c, 0x75, 0x1d, 0x49, 0x8e, 0xb5, 0x7c, 0x3e, 0xf3, 0x23, 0x0f,
	0xae, 0xa9, 0x28, 0xcd, 0xe7, 0x5a, 0x43, 0x9d, 0xfa, 0x2a, 0xdc, 0x8f, 0xf0, 0x74, 0x4d, 0xee,
	0xa2, 0xb3, 0x23, 0xe8, 0x71, 0x07, 0x4a, 0x18, 0xbc, 0xa5, 0x5a, 0x6b, 0x85, 0xc1, 0x7d, 0x01,
	0x78, 0x4a, 0x31, 0x69, 0xba, 0x0f, 0x87, 0xfb, 0x12, 0x76, 0x1b, 0x5e, 0x45, 0xfe, 0x96, 0xdb,
	0xf8, 0x8f, 0x59, 0x6c, 0xf6, 0x2b, 0xa5, 0x3f, 0x17, 0x2f, 0xee, 0x1d, 0x0c, 0xaa, 0xfd, 0xe0,
	0xde, 0xba, 0x37, 0xe2, 0x3c, 0x6e, 0xa9, 0x79, 0x6a, 0xf7, 0x01, 0xbe, 0x86, 0x7e, 0x89, 0x1a,
	0x77, 0x17, 0x4e, 0xad, 0x9d, 0x39, 0x7b, 0x4d, 0xb1, 0x0a, 0xf4, 0x61, 0x67, 0x05, 0x09, 0x1e,
	0x14, 0xce, 0x6b, 0xb7, 0xe0, 0x3c, 0xbb, 0xc3, 0x5a, 0xe5, 0xfc, 0x04, 0x76, 0x0d, 0x00, 0xee,
	0x2f, 0xfc, 0x57, 0xb9, 0x39, 0x4f, 0x56, 0xf4, 0x32, 0xc3, 0xa4, 0xc7, 0x5f, 0xc1, 0xc9, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x08, 0xf8, 0x34, 0x40, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	PostOrder(ctx context.Context, in *PostOrderRequest, opts ...grpc.CallOption) (*PostOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	GetMultipleOrders(ctx context.Context, in *GetMultipleOrdersRequest, opts ...grpc.CallOption) (*GetMultipleOrdersResponse, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) PostOrder(ctx context.Context, in *PostOrderRequest, opts ...grpc.CallOption) (*PostOrderResponse, error) {
	out := new(PostOrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/PostOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetMultipleOrders(ctx context.Context, in *GetMultipleOrdersRequest, opts ...grpc.CallOption) (*GetMultipleOrdersResponse, error) {
	out := new(GetMultipleOrdersResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetMultipleOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderRequest, opts ...grpc.CallOption) (*DeleteOrderResponse, error) {
	out := new(DeleteOrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	PostOrder(context.Context, *PostOrderRequest) (*PostOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetMultipleOrders(context.Context, *GetMultipleOrdersRequest) (*GetMultipleOrdersResponse, error)
	DeleteOrder(context.Context, *DeleteOrderRequest) (*DeleteOrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) PostOrder(ctx context.Context, req *PostOrderRequest) (*PostOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostOrder not implemented")
}
func (*UnimplementedOrderServiceServer) GetOrder(ctx context.Context, req *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (*UnimplementedOrderServiceServer) GetMultipleOrders(ctx context.Context, req *GetMultipleOrdersRequest) (*GetMultipleOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleOrders not implemented")
}
func (*UnimplementedOrderServiceServer) DeleteOrder(ctx context.Context, req *DeleteOrderRequest) (*DeleteOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_PostOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).PostOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/PostOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).PostOrder(ctx, req.(*PostOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetMultipleOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetMultipleOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetMultipleOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetMultipleOrders(ctx, req.(*GetMultipleOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeleteOrder(ctx, req.(*DeleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostOrder",
			Handler:    _OrderService_PostOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "GetMultipleOrders",
			Handler:    _OrderService_GetMultipleOrders_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _OrderService_DeleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
