// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Task) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PostTaskRequest struct {
	Text                 string               `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Timestamp            int64                `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostTaskRequest) Reset()         { *m = PostTaskRequest{} }
func (m *PostTaskRequest) String() string { return proto.CompactTextString(m) }
func (*PostTaskRequest) ProtoMessage()    {}
func (*PostTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *PostTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTaskRequest.Unmarshal(m, b)
}
func (m *PostTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTaskRequest.Marshal(b, m, deterministic)
}
func (m *PostTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTaskRequest.Merge(m, src)
}
func (m *PostTaskRequest) XXX_Size() int {
	return xxx_messageInfo_PostTaskRequest.Size(m)
}
func (m *PostTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostTaskRequest proto.InternalMessageInfo

func (m *PostTaskRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PostTaskRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *PostTaskRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type PostTaskResponse struct {
	Task                 string   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Confirmation         int64    `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostTaskResponse) Reset()         { *m = PostTaskResponse{} }
func (m *PostTaskResponse) String() string { return proto.CompactTextString(m) }
func (*PostTaskResponse) ProtoMessage()    {}
func (*PostTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *PostTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostTaskResponse.Unmarshal(m, b)
}
func (m *PostTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostTaskResponse.Marshal(b, m, deterministic)
}
func (m *PostTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostTaskResponse.Merge(m, src)
}
func (m *PostTaskResponse) XXX_Size() int {
	return xxx_messageInfo_PostTaskResponse.Size(m)
}
func (m *PostTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostTaskResponse proto.InternalMessageInfo

func (m *PostTaskResponse) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *PostTaskResponse) GetConfirmation() int64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

type GetTaskRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetTaskRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Confirmation         int64    `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskResponse) Reset()         { *m = GetTaskResponse{} }
func (m *GetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskResponse) ProtoMessage()    {}
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *GetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResponse.Unmarshal(m, b)
}
func (m *GetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResponse.Merge(m, src)
}
func (m *GetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskResponse.Size(m)
}
func (m *GetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResponse proto.InternalMessageInfo

func (m *GetTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *GetTaskResponse) GetConfirmation() int64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

type GetMultipleTaskRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleTaskRequest) Reset()         { *m = GetMultipleTaskRequest{} }
func (m *GetMultipleTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleTaskRequest) ProtoMessage()    {}
func (*GetMultipleTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *GetMultipleTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleTaskRequest.Unmarshal(m, b)
}
func (m *GetMultipleTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleTaskRequest.Merge(m, src)
}
func (m *GetMultipleTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleTaskRequest.Size(m)
}
func (m *GetMultipleTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleTaskRequest proto.InternalMessageInfo

func (m *GetMultipleTaskRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetMultipleTaskRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetMultipleTaskResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Confirmation         int64    `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleTaskResponse) Reset()         { *m = GetMultipleTaskResponse{} }
func (m *GetMultipleTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleTaskResponse) ProtoMessage()    {}
func (*GetMultipleTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *GetMultipleTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleTaskResponse.Unmarshal(m, b)
}
func (m *GetMultipleTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleTaskResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleTaskResponse.Merge(m, src)
}
func (m *GetMultipleTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleTaskResponse.Size(m)
}
func (m *GetMultipleTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleTaskResponse proto.InternalMessageInfo

func (m *GetMultipleTaskResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *GetMultipleTaskResponse) GetConfirmation() int64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

type PutTaskRequest struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string               `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutTaskRequest) Reset()         { *m = PutTaskRequest{} }
func (m *PutTaskRequest) String() string { return proto.CompactTextString(m) }
func (*PutTaskRequest) ProtoMessage()    {}
func (*PutTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *PutTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutTaskRequest.Unmarshal(m, b)
}
func (m *PutTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutTaskRequest.Marshal(b, m, deterministic)
}
func (m *PutTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutTaskRequest.Merge(m, src)
}
func (m *PutTaskRequest) XXX_Size() int {
	return xxx_messageInfo_PutTaskRequest.Size(m)
}
func (m *PutTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutTaskRequest proto.InternalMessageInfo

func (m *PutTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PutTaskRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PutTaskRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PutTaskResponse struct {
	Task                 string   `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Confirmation         int64    `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutTaskResponse) Reset()         { *m = PutTaskResponse{} }
func (m *PutTaskResponse) String() string { return proto.CompactTextString(m) }
func (*PutTaskResponse) ProtoMessage()    {}
func (*PutTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *PutTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutTaskResponse.Unmarshal(m, b)
}
func (m *PutTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutTaskResponse.Marshal(b, m, deterministic)
}
func (m *PutTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutTaskResponse.Merge(m, src)
}
func (m *PutTaskResponse) XXX_Size() int {
	return xxx_messageInfo_PutTaskResponse.Size(m)
}
func (m *PutTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutTaskResponse proto.InternalMessageInfo

func (m *PutTaskResponse) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *PutTaskResponse) GetConfirmation() int64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

type DeleteTaskRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Confirmation         int64    `protobuf:"varint,2,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResponse) Reset()         { *m = DeleteTaskResponse{} }
func (m *DeleteTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResponse) ProtoMessage()    {}
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{10}
}

func (m *DeleteTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResponse.Unmarshal(m, b)
}
func (m *DeleteTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResponse.Merge(m, src)
}
func (m *DeleteTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResponse.Size(m)
}
func (m *DeleteTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResponse proto.InternalMessageInfo

func (m *DeleteTaskResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteTaskResponse) GetConfirmation() int64 {
	if m != nil {
		return m.Confirmation
	}
	return 0
}

func init() {
	proto.RegisterType((*Task)(nil), "pb.Task")
	proto.RegisterType((*PostTaskRequest)(nil), "pb.PostTaskRequest")
	proto.RegisterType((*PostTaskResponse)(nil), "pb.PostTaskResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "pb.GetTaskRequest")
	proto.RegisterType((*GetTaskResponse)(nil), "pb.GetTaskResponse")
	proto.RegisterType((*GetMultipleTaskRequest)(nil), "pb.GetMultipleTaskRequest")
	proto.RegisterType((*GetMultipleTaskResponse)(nil), "pb.GetMultipleTaskResponse")
	proto.RegisterType((*PutTaskRequest)(nil), "pb.PutTaskRequest")
	proto.RegisterType((*PutTaskResponse)(nil), "pb.PutTaskResponse")
	proto.RegisterType((*DeleteTaskRequest)(nil), "pb.DeleteTaskRequest")
	proto.RegisterType((*DeleteTaskResponse)(nil), "pb.DeleteTaskResponse")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0x0f, 0x4a, 0x3b, 0x81, 0x04, 0xb6, 0x10, 0x2c, 0x53, 0x81, 0xb5, 0x5c, 0x72,
	0x72, 0xa5, 0x80, 0x04, 0x17, 0x24, 0x0e, 0x95, 0x4a, 0x11, 0x48, 0xd5, 0xb6, 0x27, 0x24, 0x0e,
	0x76, 0x33, 0xad, 0x56, 0x76, 0xb2, 0xc6, 0xbb, 0x46, 0xfc, 0x3b, 0xfe, 0x1a, 0xda, 0xf5, 0xda,
	0xb1, 0xdd, 0xa8, 0xb2, 0x04, 0xb7, 0xcd, 0x78, 0xe6, 0x7d, 0x9f, 0xf9, 0x08, 0x80, 0x4a, 0x64,
	0x16, 0x17, 0xa5, 0x50, 0x82, 0xb8, 0x45, 0x1a, 0xbe, 0xbe, 0x15, 0xe2, 0x36, 0xc7, 0x13, 0x13,
	0x49, 0xab, 0x9b, 0x13, 0xc5, 0xd7, 0x28, 0x55, 0xb2, 0x2e, 0xea, 0x24, 0xfa, 0x1d, 0xfc, 0xab,
	0x44, 0x66, 0x64, 0x0a, 0x2e, 0x5f, 0x05, 0x4e, 0xe4, 0x2c, 0x1e, 0x33, 0x97, 0xaf, 0x08, 0x01,
	0x5f, 0xe1, 0x6f, 0x15, 0xb8, 0x91, 0xb3, 0x38, 0x64, 0xe6, 0x4d, 0x62, 0xf0, 0x75, 0x79, 0xe0,
	0x45, 0xce, 0x62, 0xb2, 0x0c, 0xe3, 0x5a, 0x3b, 0x6e, 0xb4, 0xe3, 0xab, 0x46, 0x9b, 0x99, 0x3c,
	0x2a, 0x61, 0x76, 0x21, 0xa4, 0xd2, 0xfa, 0x0c, 0x7f, 0x56, 0x28, 0x55, 0x2b, 0xeb, 0xec, 0x90,
	0x75, 0xc7, 0xc9, 0x92, 0x63, 0x38, 0x6c, 0xbb, 0x30, 0x2c, 0x1e, 0xdb, 0x06, 0xe8, 0x17, 0x78,
	0xb2, 0x35, 0x95, 0x85, 0xd8, 0x48, 0x34, 0xae, 0x89, 0xcc, 0x5a, 0x57, 0xdd, 0x30, 0x85, 0x47,
	0xd7, 0x62, 0x73, 0xc3, 0xcb, 0x75, 0xa2, 0xb8, 0xd8, 0x18, 0x77, 0x8f, 0xf5, 0x62, 0xf4, 0x03,
	0x4c, 0xcf, 0xb0, 0xc7, 0x3f, 0x1c, 0xd3, 0x1c, 0xf6, 0x2b, 0x89, 0xe5, 0xf9, 0xa9, 0xa9, 0xf7,
	0x99, 0xfd, 0x45, 0x2f, 0x61, 0xd6, 0x56, 0x5a, 0x88, 0xe3, 0x0e, 0xc4, 0x64, 0x79, 0x10, 0x17,
	0x69, 0x6c, 0xbe, 0x8f, 0xc7, 0xf9, 0x04, 0xf3, 0x33, 0x54, 0xdf, 0xaa, 0x5c, 0xf1, 0x22, 0xc7,
	0xc1, 0x58, 0x65, 0xc6, 0x0b, 0xa3, 0xed, 0x33, 0xf3, 0xae, 0x9b, 0xce, 0xd0, 0x82, 0x99, 0x37,
	0xfd, 0x01, 0x2f, 0xee, 0x28, 0x58, 0xbc, 0x57, 0xf0, 0x40, 0x83, 0xc8, 0xc0, 0x89, 0xbc, 0x1e,
	0x5f, 0x1d, 0x1e, 0x05, 0xb8, 0x82, 0xe9, 0x45, 0x75, 0xef, 0xbc, 0xfe, 0xc7, 0x59, 0x9d, 0xc3,
	0xac, 0x75, 0xf9, 0xc7, 0x05, 0xbf, 0x81, 0xa7, 0xa7, 0x98, 0xa3, 0xc2, 0x7b, 0x98, 0xe9, 0x67,
	0x20, 0xdd, 0x24, 0x6b, 0x39, 0xec, 0x6c, 0x84, 0xdd, 0xf2, 0x8f, 0x0b, 0x13, 0x2d, 0x72, 0x89,
	0xe5, 0x2f, 0x7e, 0x8d, 0xe4, 0x3d, 0x1c, 0x34, 0xb7, 0x4a, 0x8e, 0xf4, 0xc0, 0x07, 0x7f, 0x97,
	0xf0, 0x59, 0x3f, 0x58, 0x5b, 0xd3, 0x3d, 0xf2, 0x0e, 0x1e, 0xda, 0xf3, 0x22, 0x44, 0xa7, 0xf4,
	0xaf, 0x34, 0x3c, 0xea, 0xc5, 0xda, 0xaa, 0xaf, 0xe6, 0x28, 0xbb, 0xdb, 0x27, 0xa1, 0xcd, 0xdc,
	0x71, 0x54, 0xe1, 0xcb, 0x9d, 0xdf, 0xba, 0x0c, 0x76, 0x0d, 0x35, 0x43, 0x7f, 0xf3, 0x35, 0xc3,
	0x60, 0x4f, 0x74, 0x8f, 0x7c, 0x04, 0xd8, 0x0e, 0x93, 0x3c, 0xd7, 0x49, 0x77, 0x36, 0x10, 0xce,
	0x87, 0xe1, 0xa6, 0x3c, 0xdd, 0x37, 0x57, 0xf1, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d,
	0xb3, 0xd9, 0x9c, 0xe8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	PostTask(ctx context.Context, in *PostTaskRequest, opts ...grpc.CallOption) (*PostTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	GetMultipleTask(ctx context.Context, in *GetMultipleTaskRequest, opts ...grpc.CallOption) (*GetMultipleTaskResponse, error)
	PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) PostTask(ctx context.Context, in *PostTaskRequest, opts ...grpc.CallOption) (*PostTaskResponse, error) {
	out := new(PostTaskResponse)
	err := c.cc.Invoke(ctx, "/pb.TaskService/PostTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, "/pb.TaskService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetMultipleTask(ctx context.Context, in *GetMultipleTaskRequest, opts ...grpc.CallOption) (*GetMultipleTaskResponse, error) {
	out := new(GetMultipleTaskResponse)
	err := c.cc.Invoke(ctx, "/pb.TaskService/GetMultipleTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) PutTask(ctx context.Context, in *PutTaskRequest, opts ...grpc.CallOption) (*PutTaskResponse, error) {
	out := new(PutTaskResponse)
	err := c.cc.Invoke(ctx, "/pb.TaskService/PutTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, "/pb.TaskService/DeleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	PostTask(context.Context, *PostTaskRequest) (*PostTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	GetMultipleTask(context.Context, *GetMultipleTaskRequest) (*GetMultipleTaskResponse, error)
	PutTask(context.Context, *PutTaskRequest) (*PutTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
}

// UnimplementedTaskServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (*UnimplementedTaskServiceServer) PostTask(ctx context.Context, req *PostTaskRequest) (*PostTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTask not implemented")
}
func (*UnimplementedTaskServiceServer) GetTask(ctx context.Context, req *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (*UnimplementedTaskServiceServer) GetMultipleTask(ctx context.Context, req *GetMultipleTaskRequest) (*GetMultipleTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleTask not implemented")
}
func (*UnimplementedTaskServiceServer) PutTask(ctx context.Context, req *PutTaskRequest) (*PutTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutTask not implemented")
}
func (*UnimplementedTaskServiceServer) DeleteTask(ctx context.Context, req *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_PostTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).PostTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TaskService/PostTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).PostTask(ctx, req.(*PostTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TaskService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetMultipleTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetMultipleTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TaskService/GetMultipleTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetMultipleTask(ctx, req.(*GetMultipleTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_PutTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).PutTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TaskService/PutTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).PutTask(ctx, req.(*PutTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TaskService/DeleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostTask",
			Handler:    _TaskService_PostTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "GetMultipleTask",
			Handler:    _TaskService_GetMultipleTask_Handler,
		},
		{
			MethodName: "PutTask",
			Handler:    _TaskService_PutTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _TaskService_DeleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
