// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goal.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Goal struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator              string               `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Participants         []string             `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Likes                []string             `protobuf:"bytes,4,rep,name=likes,proto3" json:"likes,omitempty"`
	Watchers             []string             `protobuf:"bytes,5,rep,name=watchers,proto3" json:"watchers,omitempty"`
	Aim                  string               `protobuf:"bytes,6,opt,name=aim,proto3" json:"aim,omitempty"`
	Reason               string               `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Details              string               `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	Inspiration          string               `protobuf:"bytes,9,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	Type                 string               `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	Tags                 []string             `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	SimilarGoals         []string             `protobuf:"bytes,12,rep,name=similarGoals,proto3" json:"similarGoals,omitempty"`
	IsAchieved           bool                 `protobuf:"varint,13,opt,name=isAchieved,proto3" json:"isAchieved,omitempty"`
	IsPrivate            bool                 `protobuf:"varint,14,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,15,opt,name=date,proto3" json:"date,omitempty"`
	GoalJourney          *Journey             `protobuf:"bytes,16,opt,name=goalJourney,proto3" json:"goalJourney,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Goal) Reset()         { *m = Goal{} }
func (m *Goal) String() string { return proto.CompactTextString(m) }
func (*Goal) ProtoMessage()    {}
func (*Goal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{0}
}

func (m *Goal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goal.Unmarshal(m, b)
}
func (m *Goal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goal.Marshal(b, m, deterministic)
}
func (m *Goal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goal.Merge(m, src)
}
func (m *Goal) XXX_Size() int {
	return xxx_messageInfo_Goal.Size(m)
}
func (m *Goal) XXX_DiscardUnknown() {
	xxx_messageInfo_Goal.DiscardUnknown(m)
}

var xxx_messageInfo_Goal proto.InternalMessageInfo

func (m *Goal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Goal) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Goal) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *Goal) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *Goal) GetWatchers() []string {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *Goal) GetAim() string {
	if m != nil {
		return m.Aim
	}
	return ""
}

func (m *Goal) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Goal) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Goal) GetInspiration() string {
	if m != nil {
		return m.Inspiration
	}
	return ""
}

func (m *Goal) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Goal) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Goal) GetSimilarGoals() []string {
	if m != nil {
		return m.SimilarGoals
	}
	return nil
}

func (m *Goal) GetIsAchieved() bool {
	if m != nil {
		return m.IsAchieved
	}
	return false
}

func (m *Goal) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *Goal) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Goal) GetGoalJourney() *Journey {
	if m != nil {
		return m.GoalJourney
	}
	return nil
}

type Journey struct {
	IsComplete           bool                 `protobuf:"varint,1,opt,name=isComplete,proto3" json:"isComplete,omitempty"`
	IsInProgress         bool                 `protobuf:"varint,2,opt,name=IsInProgress,proto3" json:"IsInProgress,omitempty"`
	IsStarted            bool                 `protobuf:"varint,3,opt,name=IsStarted,proto3" json:"IsStarted,omitempty"`
	Details              string               `protobuf:"bytes,4,opt,name=Details,proto3" json:"Details,omitempty"`
	Typ                  string               `protobuf:"bytes,5,opt,name=typ,proto3" json:"typ,omitempty"`
	Steps                []string             `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	Progress             int32                `protobuf:"varint,7,opt,name=progress,proto3" json:"progress,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=startDate,proto3" json:"startDate,omitempty"`
	DueDate              *timestamp.Timestamp `protobuf:"bytes,9,opt,name=dueDate,proto3" json:"dueDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Journey) Reset()         { *m = Journey{} }
func (m *Journey) String() string { return proto.CompactTextString(m) }
func (*Journey) ProtoMessage()    {}
func (*Journey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{1}
}

func (m *Journey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Journey.Unmarshal(m, b)
}
func (m *Journey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Journey.Marshal(b, m, deterministic)
}
func (m *Journey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Journey.Merge(m, src)
}
func (m *Journey) XXX_Size() int {
	return xxx_messageInfo_Journey.Size(m)
}
func (m *Journey) XXX_DiscardUnknown() {
	xxx_messageInfo_Journey.DiscardUnknown(m)
}

var xxx_messageInfo_Journey proto.InternalMessageInfo

func (m *Journey) GetIsComplete() bool {
	if m != nil {
		return m.IsComplete
	}
	return false
}

func (m *Journey) GetIsInProgress() bool {
	if m != nil {
		return m.IsInProgress
	}
	return false
}

func (m *Journey) GetIsStarted() bool {
	if m != nil {
		return m.IsStarted
	}
	return false
}

func (m *Journey) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Journey) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *Journey) GetSteps() []string {
	if m != nil {
		return m.Steps
	}
	return nil
}

func (m *Journey) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *Journey) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Journey) GetDueDate() *timestamp.Timestamp {
	if m != nil {
		return m.DueDate
	}
	return nil
}

type PostGoalRequest struct {
	Creator              string               `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Participants         []string             `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	Likes                []string             `protobuf:"bytes,3,rep,name=likes,proto3" json:"likes,omitempty"`
	Watchers             []string             `protobuf:"bytes,4,rep,name=watchers,proto3" json:"watchers,omitempty"`
	Aim                  string               `protobuf:"bytes,5,opt,name=aim,proto3" json:"aim,omitempty"`
	Reason               string               `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Details              string               `protobuf:"bytes,7,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	Inspiration          string               `protobuf:"bytes,9,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	Tags                 []string             `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	SimilarGoals         []string             `protobuf:"bytes,11,rep,name=similarGoals,proto3" json:"similarGoals,omitempty"`
	IsAchieved           bool                 `protobuf:"varint,12,opt,name=isAchieved,proto3" json:"isAchieved,omitempty"`
	IsPrivate            bool                 `protobuf:"varint,13,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	Journey              *Journey             `protobuf:"bytes,14,opt,name=journey,proto3" json:"journey,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,15,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostGoalRequest) Reset()         { *m = PostGoalRequest{} }
func (m *PostGoalRequest) String() string { return proto.CompactTextString(m) }
func (*PostGoalRequest) ProtoMessage()    {}
func (*PostGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{2}
}

func (m *PostGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostGoalRequest.Unmarshal(m, b)
}
func (m *PostGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostGoalRequest.Marshal(b, m, deterministic)
}
func (m *PostGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostGoalRequest.Merge(m, src)
}
func (m *PostGoalRequest) XXX_Size() int {
	return xxx_messageInfo_PostGoalRequest.Size(m)
}
func (m *PostGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostGoalRequest proto.InternalMessageInfo

func (m *PostGoalRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PostGoalRequest) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *PostGoalRequest) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *PostGoalRequest) GetWatchers() []string {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *PostGoalRequest) GetAim() string {
	if m != nil {
		return m.Aim
	}
	return ""
}

func (m *PostGoalRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PostGoalRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *PostGoalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PostGoalRequest) GetInspiration() string {
	if m != nil {
		return m.Inspiration
	}
	return ""
}

func (m *PostGoalRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PostGoalRequest) GetSimilarGoals() []string {
	if m != nil {
		return m.SimilarGoals
	}
	return nil
}

func (m *PostGoalRequest) GetIsAchieved() bool {
	if m != nil {
		return m.IsAchieved
	}
	return false
}

func (m *PostGoalRequest) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *PostGoalRequest) GetJourney() *Journey {
	if m != nil {
		return m.Journey
	}
	return nil
}

func (m *PostGoalRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PostGoalResponse struct {
	Goal                 string   `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostGoalResponse) Reset()         { *m = PostGoalResponse{} }
func (m *PostGoalResponse) String() string { return proto.CompactTextString(m) }
func (*PostGoalResponse) ProtoMessage()    {}
func (*PostGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{3}
}

func (m *PostGoalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostGoalResponse.Unmarshal(m, b)
}
func (m *PostGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostGoalResponse.Marshal(b, m, deterministic)
}
func (m *PostGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostGoalResponse.Merge(m, src)
}
func (m *PostGoalResponse) XXX_Size() int {
	return xxx_messageInfo_PostGoalResponse.Size(m)
}
func (m *PostGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostGoalResponse proto.InternalMessageInfo

func (m *PostGoalResponse) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

type GetGoalRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoalRequest) Reset()         { *m = GetGoalRequest{} }
func (m *GetGoalRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoalRequest) ProtoMessage()    {}
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{4}
}

func (m *GetGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalRequest.Unmarshal(m, b)
}
func (m *GetGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalRequest.Marshal(b, m, deterministic)
}
func (m *GetGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalRequest.Merge(m, src)
}
func (m *GetGoalRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoalRequest.Size(m)
}
func (m *GetGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalRequest proto.InternalMessageInfo

func (m *GetGoalRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetGoalRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetGoalResponse struct {
	Goal                 *Goal    `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoalResponse) Reset()         { *m = GetGoalResponse{} }
func (m *GetGoalResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoalResponse) ProtoMessage()    {}
func (*GetGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{5}
}

func (m *GetGoalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalResponse.Unmarshal(m, b)
}
func (m *GetGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalResponse.Marshal(b, m, deterministic)
}
func (m *GetGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalResponse.Merge(m, src)
}
func (m *GetGoalResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoalResponse.Size(m)
}
func (m *GetGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalResponse proto.InternalMessageInfo

func (m *GetGoalResponse) GetGoal() *Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

type GetMultipleGoalsRequest struct {
	Skip                 uint64   `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 uint64   `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleGoalsRequest) Reset()         { *m = GetMultipleGoalsRequest{} }
func (m *GetMultipleGoalsRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultipleGoalsRequest) ProtoMessage()    {}
func (*GetMultipleGoalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{6}
}

func (m *GetMultipleGoalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleGoalsRequest.Unmarshal(m, b)
}
func (m *GetMultipleGoalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleGoalsRequest.Marshal(b, m, deterministic)
}
func (m *GetMultipleGoalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleGoalsRequest.Merge(m, src)
}
func (m *GetMultipleGoalsRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultipleGoalsRequest.Size(m)
}
func (m *GetMultipleGoalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleGoalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleGoalsRequest proto.InternalMessageInfo

func (m *GetMultipleGoalsRequest) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetMultipleGoalsRequest) GetTake() uint64 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetMultipleGoalsResponse struct {
	Goals                []*Goal  `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultipleGoalsResponse) Reset()         { *m = GetMultipleGoalsResponse{} }
func (m *GetMultipleGoalsResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultipleGoalsResponse) ProtoMessage()    {}
func (*GetMultipleGoalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{7}
}

func (m *GetMultipleGoalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultipleGoalsResponse.Unmarshal(m, b)
}
func (m *GetMultipleGoalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultipleGoalsResponse.Marshal(b, m, deterministic)
}
func (m *GetMultipleGoalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultipleGoalsResponse.Merge(m, src)
}
func (m *GetMultipleGoalsResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultipleGoalsResponse.Size(m)
}
func (m *GetMultipleGoalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultipleGoalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultipleGoalsResponse proto.InternalMessageInfo

func (m *GetMultipleGoalsResponse) GetGoals() []*Goal {
	if m != nil {
		return m.Goals
	}
	return nil
}

type PutGoalRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator              string               `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Participants         []string             `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	Likes                []string             `protobuf:"bytes,4,rep,name=likes,proto3" json:"likes,omitempty"`
	Watchers             []string             `protobuf:"bytes,5,rep,name=watchers,proto3" json:"watchers,omitempty"`
	Aim                  string               `protobuf:"bytes,6,opt,name=aim,proto3" json:"aim,omitempty"`
	Reason               string               `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Details              string               `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	Type                 string               `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Inspiration          string               `protobuf:"bytes,10,opt,name=inspiration,proto3" json:"inspiration,omitempty"`
	Tags                 []string             `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	SimilarGoals         []string             `protobuf:"bytes,12,rep,name=similarGoals,proto3" json:"similarGoals,omitempty"`
	IsAchieved           bool                 `protobuf:"varint,13,opt,name=isAchieved,proto3" json:"isAchieved,omitempty"`
	IsPrivate            bool                 `protobuf:"varint,14,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
	Journey              *Journey             `protobuf:"bytes,15,opt,name=journey,proto3" json:"journey,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,16,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PutGoalRequest) Reset()         { *m = PutGoalRequest{} }
func (m *PutGoalRequest) String() string { return proto.CompactTextString(m) }
func (*PutGoalRequest) ProtoMessage()    {}
func (*PutGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{8}
}

func (m *PutGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutGoalRequest.Unmarshal(m, b)
}
func (m *PutGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutGoalRequest.Marshal(b, m, deterministic)
}
func (m *PutGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutGoalRequest.Merge(m, src)
}
func (m *PutGoalRequest) XXX_Size() int {
	return xxx_messageInfo_PutGoalRequest.Size(m)
}
func (m *PutGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutGoalRequest proto.InternalMessageInfo

func (m *PutGoalRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PutGoalRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *PutGoalRequest) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

func (m *PutGoalRequest) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *PutGoalRequest) GetWatchers() []string {
	if m != nil {
		return m.Watchers
	}
	return nil
}

func (m *PutGoalRequest) GetAim() string {
	if m != nil {
		return m.Aim
	}
	return ""
}

func (m *PutGoalRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PutGoalRequest) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *PutGoalRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PutGoalRequest) GetInspiration() string {
	if m != nil {
		return m.Inspiration
	}
	return ""
}

func (m *PutGoalRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *PutGoalRequest) GetSimilarGoals() []string {
	if m != nil {
		return m.SimilarGoals
	}
	return nil
}

func (m *PutGoalRequest) GetIsAchieved() bool {
	if m != nil {
		return m.IsAchieved
	}
	return false
}

func (m *PutGoalRequest) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *PutGoalRequest) GetJourney() *Journey {
	if m != nil {
		return m.Journey
	}
	return nil
}

func (m *PutGoalRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type PutGoalResponse struct {
	Goal                 string   `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutGoalResponse) Reset()         { *m = PutGoalResponse{} }
func (m *PutGoalResponse) String() string { return proto.CompactTextString(m) }
func (*PutGoalResponse) ProtoMessage()    {}
func (*PutGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{9}
}

func (m *PutGoalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutGoalResponse.Unmarshal(m, b)
}
func (m *PutGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutGoalResponse.Marshal(b, m, deterministic)
}
func (m *PutGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutGoalResponse.Merge(m, src)
}
func (m *PutGoalResponse) XXX_Size() int {
	return xxx_messageInfo_PutGoalResponse.Size(m)
}
func (m *PutGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutGoalResponse proto.InternalMessageInfo

func (m *PutGoalResponse) GetGoal() string {
	if m != nil {
		return m.Goal
	}
	return ""
}

type DeleteGoalRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGoalRequest) Reset()         { *m = DeleteGoalRequest{} }
func (m *DeleteGoalRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGoalRequest) ProtoMessage()    {}
func (*DeleteGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{10}
}

func (m *DeleteGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGoalRequest.Unmarshal(m, b)
}
func (m *DeleteGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGoalRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGoalRequest.Merge(m, src)
}
func (m *DeleteGoalRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGoalRequest.Size(m)
}
func (m *DeleteGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGoalRequest proto.InternalMessageInfo

func (m *DeleteGoalRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteGoalResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGoalResponse) Reset()         { *m = DeleteGoalResponse{} }
func (m *DeleteGoalResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGoalResponse) ProtoMessage()    {}
func (*DeleteGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9190ce9949371de, []int{11}
}

func (m *DeleteGoalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGoalResponse.Unmarshal(m, b)
}
func (m *DeleteGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGoalResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGoalResponse.Merge(m, src)
}
func (m *DeleteGoalResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGoalResponse.Size(m)
}
func (m *DeleteGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGoalResponse proto.InternalMessageInfo

func (m *DeleteGoalResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Goal)(nil), "pb.Goal")
	proto.RegisterType((*Journey)(nil), "pb.Journey")
	proto.RegisterType((*PostGoalRequest)(nil), "pb.PostGoalRequest")
	proto.RegisterType((*PostGoalResponse)(nil), "pb.PostGoalResponse")
	proto.RegisterType((*GetGoalRequest)(nil), "pb.GetGoalRequest")
	proto.RegisterType((*GetGoalResponse)(nil), "pb.GetGoalResponse")
	proto.RegisterType((*GetMultipleGoalsRequest)(nil), "pb.GetMultipleGoalsRequest")
	proto.RegisterType((*GetMultipleGoalsResponse)(nil), "pb.GetMultipleGoalsResponse")
	proto.RegisterType((*PutGoalRequest)(nil), "pb.PutGoalRequest")
	proto.RegisterType((*PutGoalResponse)(nil), "pb.PutGoalResponse")
	proto.RegisterType((*DeleteGoalRequest)(nil), "pb.DeleteGoalRequest")
	proto.RegisterType((*DeleteGoalResponse)(nil), "pb.DeleteGoalResponse")
}

func init() { proto.RegisterFile("goal.proto", fileDescriptor_a9190ce9949371de) }

var fileDescriptor_a9190ce9949371de = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xd1, 0x6e, 0x22, 0x37,
	0x14, 0x0d, 0xcc, 0x00, 0xc3, 0x9d, 0x04, 0xa8, 0x93, 0xa6, 0x16, 0x8d, 0x52, 0x34, 0x6d, 0x2a,
	0x5e, 0x4a, 0xa4, 0xb4, 0x52, 0xa3, 0x4a, 0x7d, 0x88, 0x8a, 0x14, 0x51, 0xa9, 0x2a, 0x9a, 0xf4,
	0x07, 0x06, 0x70, 0x89, 0x9b, 0x81, 0x71, 0xc7, 0x26, 0x2b, 0x3e, 0x6d, 0x5f, 0xf7, 0x69, 0x7f,
	0x60, 0xb5, 0xbf, 0xb3, 0xf2, 0xb5, 0x07, 0x66, 0x08, 0x10, 0x9e, 0x56, 0xda, 0x37, 0xdf, 0x73,
	0xaf, 0x7d, 0xed, 0x7b, 0xce, 0x31, 0xc0, 0x34, 0x89, 0xe2, 0x9e, 0x48, 0x13, 0x95, 0x90, 0xb2,
	0x18, 0xb5, 0xbf, 0x9b, 0x26, 0xc9, 0x34, 0x66, 0xd7, 0x88, 0x8c, 0x16, 0xff, 0x5e, 0x2b, 0x3e,
	0x63, 0x52, 0x45, 0x33, 0x61, 0x8a, 0x82, 0x0f, 0x0e, 0xb8, 0xf7, 0x49, 0x14, 0x93, 0x06, 0x94,
	0xf9, 0x84, 0x96, 0x3a, 0xa5, 0x6e, 0x3d, 0x2c, 0xf3, 0x09, 0xa1, 0x50, 0x1b, 0xa7, 0x2c, 0x52,
	0x49, 0x4a, 0xcb, 0x08, 0x66, 0x21, 0x09, 0xe0, 0x58, 0x44, 0xa9, 0xe2, 0x63, 0x2e, 0xa2, 0xb9,
	0x92, 0xd4, 0xe9, 0x38, 0xdd, 0x7a, 0x58, 0xc0, 0xc8, 0x19, 0x54, 0x62, 0xfe, 0xc4, 0x24, 0x75,
	0x31, 0x69, 0x02, 0xd2, 0x06, 0xef, 0x4d, 0xa4, 0xc6, 0x8f, 0x2c, 0x95, 0xb4, 0x82, 0x89, 0x55,
	0x4c, 0x5a, 0xe0, 0x44, 0x7c, 0x46, 0xab, 0xd8, 0x4b, 0x2f, 0xc9, 0x39, 0x54, 0x53, 0x16, 0xc9,
	0x64, 0x4e, 0x6b, 0x08, 0xda, 0x48, 0xdf, 0x6c, 0xc2, 0x54, 0xc4, 0x63, 0x49, 0x3d, 0x73, 0x33,
	0x1b, 0x92, 0x0e, 0xf8, 0x7c, 0x2e, 0x05, 0x4f, 0x23, 0xc5, 0x93, 0x39, 0xad, 0x63, 0x36, 0x0f,
	0x11, 0x02, 0xae, 0x5a, 0x0a, 0x46, 0x01, 0x53, 0xb8, 0x46, 0x2c, 0x9a, 0x4a, 0xea, 0xe3, 0x8d,
	0x70, 0xad, 0xdf, 0x28, 0xf9, 0x8c, 0xc7, 0x51, 0xaa, 0x87, 0x23, 0xe9, 0xb1, 0x79, 0x63, 0x1e,
	0x23, 0x97, 0x00, 0x5c, 0xde, 0x8d, 0x1f, 0x39, 0x7b, 0x66, 0x13, 0x7a, 0xd2, 0x29, 0x75, 0xbd,
	0x30, 0x87, 0x90, 0x0b, 0xa8, 0x73, 0x39, 0x4c, 0xf9, 0x73, 0xa4, 0x18, 0x6d, 0x60, 0x7a, 0x0d,
	0x90, 0x1e, 0xb8, 0x13, 0x9d, 0x68, 0x76, 0x4a, 0x5d, 0xff, 0xa6, 0xdd, 0x33, 0x44, 0xf5, 0x32,
	0xa2, 0x7a, 0xff, 0x64, 0x44, 0x85, 0x58, 0x47, 0x7e, 0x02, 0x5f, 0x73, 0xfb, 0x67, 0xb2, 0x48,
	0xe7, 0x6c, 0x49, 0x5b, 0xb8, 0xcd, 0xef, 0x89, 0x51, 0xcf, 0x42, 0x61, 0x3e, 0x1f, 0xbc, 0x2d,
	0x43, 0xcd, 0xae, 0xcd, 0x45, 0xff, 0x48, 0x66, 0x22, 0x66, 0x8a, 0x21, 0xc5, 0x78, 0xd1, 0x0c,
	0xd1, 0x8f, 0x1d, 0xc8, 0xc1, 0x7c, 0x98, 0x26, 0xd3, 0x94, 0x49, 0x89, 0x7c, 0x7b, 0x61, 0x01,
	0xd3, 0x8f, 0x19, 0xc8, 0x07, 0x15, 0xa5, 0x8a, 0x4d, 0xa8, 0x63, 0x1e, 0xb3, 0x02, 0x34, 0x25,
	0x7d, 0x4b, 0x89, 0x6b, 0x28, 0xb1, 0xa1, 0xa6, 0x55, 0x2d, 0x05, 0xad, 0x18, 0x5a, 0xd5, 0x52,
	0x68, 0x69, 0x48, 0xc5, 0x84, 0xa4, 0x55, 0x23, 0x0d, 0x0c, 0xb4, 0x34, 0x44, 0xd6, 0x5f, 0xd3,
	0x5d, 0x09, 0x57, 0x31, 0xb9, 0x85, 0xba, 0xd4, 0x8d, 0xfa, 0x7a, 0x5e, 0xde, 0xab, 0xf3, 0x5a,
	0x17, 0x93, 0x5f, 0xa0, 0x36, 0x59, 0x30, 0xdc, 0x57, 0x7f, 0x75, 0x5f, 0x56, 0x1a, 0xbc, 0x77,
	0xa0, 0x39, 0x4c, 0xa4, 0xd2, 0x34, 0x87, 0xec, 0xff, 0x05, 0x93, 0x2a, 0x6f, 0x87, 0xd2, 0x7e,
	0x3b, 0x94, 0xf7, 0xd9, 0xc1, 0xd9, 0x65, 0x07, 0x77, 0xbb, 0x1d, 0x2a, 0xdb, 0xec, 0x50, 0xdd,
	0x65, 0x87, 0x5a, 0xd1, 0x0e, 0x99, 0xd8, 0xbd, 0x9c, 0xd8, 0x0f, 0xb3, 0x88, 0xb6, 0x03, 0xec,
	0xb1, 0x83, 0xff, 0xaa, 0x1d, 0x8e, 0xf7, 0xdb, 0xe1, 0x64, 0xd3, 0x0e, 0x57, 0x50, 0xfb, 0xcf,
	0x4a, 0xbb, 0xf1, 0x52, 0xda, 0x59, 0x4e, 0xbb, 0x46, 0xff, 0x60, 0x87, 0xb8, 0x46, 0xd7, 0x05,
	0x3f, 0x42, 0x6b, 0xcd, 0xa4, 0x14, 0xc9, 0x5c, 0xa2, 0xdf, 0xb5, 0x53, 0x2c, 0x8f, 0xb8, 0x0e,
	0x6e, 0xa1, 0x71, 0xcf, 0x0a, 0x84, 0x6f, 0xfe, 0x87, 0xe7, 0x50, 0x5d, 0x48, 0x96, 0x0e, 0xfa,
	0x68, 0x0f, 0x37, 0xb4, 0x51, 0x70, 0x0d, 0xcd, 0xd5, 0x4e, 0xdb, 0xe0, 0x22, 0xd7, 0xc0, 0xbf,
	0xf1, 0xf4, 0x43, 0x30, 0x6f, 0x5a, 0xdd, 0xc1, 0x37, 0xf7, 0x4c, 0xfd, 0xb5, 0x88, 0x15, 0x17,
	0x31, 0xc3, 0xd9, 0x65, 0x3d, 0x09, 0xb8, 0xf2, 0x89, 0x0b, 0xdc, 0xe8, 0x86, 0xb8, 0x36, 0x74,
	0x3c, 0x31, 0xdb, 0x15, 0xd7, 0xc1, 0x6f, 0x40, 0x5f, 0x1e, 0x61, 0x9b, 0x5f, 0x42, 0x65, 0x8a,
	0x1c, 0x95, 0x3a, 0x4e, 0xa1, 0xbb, 0x81, 0x83, 0x8f, 0x0e, 0x34, 0x86, 0x8b, 0xbd, 0x4f, 0xfd,
	0x12, 0xbf, 0xfe, 0x4c, 0xeb, 0xf5, 0xdd, 0x5a, 0x87, 0xdd, 0x5a, 0xff, 0xbc, 0x5f, 0x7f, 0x4e,
	0xeb, 0xcd, 0x03, 0xb4, 0xde, 0x3a, 0x50, 0xeb, 0x57, 0xd0, 0x5c, 0x11, 0xbb, 0x47, 0xea, 0xdf,
	0xc3, 0x57, 0x7d, 0xa6, 0xff, 0xfd, 0x3d, 0x12, 0x08, 0x7e, 0x00, 0x92, 0x2f, 0xb2, 0xc7, 0x6d,
	0x54, 0xdd, 0xbc, 0x2b, 0x83, 0xaf, 0x0b, 0x1e, 0x58, 0xfa, 0xcc, 0xc7, 0x8c, 0xfc, 0x0a, 0x5e,
	0xe6, 0x36, 0x72, 0xaa, 0xdf, 0xb4, 0xf1, 0x8b, 0xb6, 0xcf, 0x8a, 0xa0, 0x39, 0x36, 0x38, 0xd2,
	0xff, 0xb4, 0x35, 0x11, 0x21, 0x28, 0xd8, 0x82, 0x17, 0xdb, 0xa7, 0x05, 0x6c, 0xb5, 0xeb, 0x6f,
	0x68, 0x6d, 0xda, 0x80, 0x7c, 0x6b, 0x4b, 0xb7, 0xf9, 0xab, 0x7d, 0xb1, 0x3d, 0x99, 0xbf, 0x86,
	0x9d, 0xa0, 0xb9, 0x46, 0xd1, 0x27, 0xe6, 0x1a, 0x1b, 0x23, 0x0e, 0x8e, 0xc8, 0xef, 0x00, 0xeb,
	0x59, 0x91, 0xaf, 0x75, 0xd1, 0x8b, 0x01, 0xb7, 0xcf, 0x37, 0xe1, 0x6c, 0xfb, 0xa8, 0x8a, 0x84,
	0xfe, 0xfc, 0x29, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x8b, 0x31, 0xc2, 0xbb, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoalServiceClient is the client API for GoalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoalServiceClient interface {
	PostGoal(ctx context.Context, in *PostGoalRequest, opts ...grpc.CallOption) (*PostGoalResponse, error)
	GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error)
	GetMultipleGoals(ctx context.Context, in *GetMultipleGoalsRequest, opts ...grpc.CallOption) (*GetMultipleGoalsResponse, error)
	PutGoal(ctx context.Context, in *PutGoalRequest, opts ...grpc.CallOption) (*PutGoalResponse, error)
	DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*DeleteGoalResponse, error)
}

type goalServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoalServiceClient(cc *grpc.ClientConn) GoalServiceClient {
	return &goalServiceClient{cc}
}

func (c *goalServiceClient) PostGoal(ctx context.Context, in *PostGoalRequest, opts ...grpc.CallOption) (*PostGoalResponse, error) {
	out := new(PostGoalResponse)
	err := c.cc.Invoke(ctx, "/pb.GoalService/PostGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*GetGoalResponse, error) {
	out := new(GetGoalResponse)
	err := c.cc.Invoke(ctx, "/pb.GoalService/GetGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetMultipleGoals(ctx context.Context, in *GetMultipleGoalsRequest, opts ...grpc.CallOption) (*GetMultipleGoalsResponse, error) {
	out := new(GetMultipleGoalsResponse)
	err := c.cc.Invoke(ctx, "/pb.GoalService/GetMultipleGoals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) PutGoal(ctx context.Context, in *PutGoalRequest, opts ...grpc.CallOption) (*PutGoalResponse, error) {
	out := new(PutGoalResponse)
	err := c.cc.Invoke(ctx, "/pb.GoalService/PutGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) DeleteGoal(ctx context.Context, in *DeleteGoalRequest, opts ...grpc.CallOption) (*DeleteGoalResponse, error) {
	out := new(DeleteGoalResponse)
	err := c.cc.Invoke(ctx, "/pb.GoalService/DeleteGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoalServiceServer is the server API for GoalService service.
type GoalServiceServer interface {
	PostGoal(context.Context, *PostGoalRequest) (*PostGoalResponse, error)
	GetGoal(context.Context, *GetGoalRequest) (*GetGoalResponse, error)
	GetMultipleGoals(context.Context, *GetMultipleGoalsRequest) (*GetMultipleGoalsResponse, error)
	PutGoal(context.Context, *PutGoalRequest) (*PutGoalResponse, error)
	DeleteGoal(context.Context, *DeleteGoalRequest) (*DeleteGoalResponse, error)
}

// UnimplementedGoalServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGoalServiceServer struct {
}

func (*UnimplementedGoalServiceServer) PostGoal(ctx context.Context, req *PostGoalRequest) (*PostGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostGoal not implemented")
}
func (*UnimplementedGoalServiceServer) GetGoal(ctx context.Context, req *GetGoalRequest) (*GetGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoal not implemented")
}
func (*UnimplementedGoalServiceServer) GetMultipleGoals(ctx context.Context, req *GetMultipleGoalsRequest) (*GetMultipleGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleGoals not implemented")
}
func (*UnimplementedGoalServiceServer) PutGoal(ctx context.Context, req *PutGoalRequest) (*PutGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutGoal not implemented")
}
func (*UnimplementedGoalServiceServer) DeleteGoal(ctx context.Context, req *DeleteGoalRequest) (*DeleteGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoal not implemented")
}

func RegisterGoalServiceServer(s *grpc.Server, srv GoalServiceServer) {
	s.RegisterService(&_GoalService_serviceDesc, srv)
}

func _GoalService_PostGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).PostGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoalService/PostGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).PostGoal(ctx, req.(*PostGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoalService/GetGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetGoal(ctx, req.(*GetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetMultipleGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetMultipleGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoalService/GetMultipleGoals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetMultipleGoals(ctx, req.(*GetMultipleGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_PutGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).PutGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoalService/PutGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).PutGoal(ctx, req.(*PutGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_DeleteGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).DeleteGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoalService/DeleteGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).DeleteGoal(ctx, req.(*DeleteGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoalService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GoalService",
	HandlerType: (*GoalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostGoal",
			Handler:    _GoalService_PostGoal_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _GoalService_GetGoal_Handler,
		},
		{
			MethodName: "GetMultipleGoals",
			Handler:    _GoalService_GetMultipleGoals_Handler,
		},
		{
			MethodName: "PutGoal",
			Handler:    _GoalService_PutGoal_Handler,
		},
		{
			MethodName: "DeleteGoal",
			Handler:    _GoalService_DeleteGoal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goal.proto",
}
